# CatBoost GPU experiments — VS Code connected to Colab

This is a separate CatBoost workflow. The existing LightGBM notebooks are unchanged.
Connect this notebook to **Colab → New Colab Server → GPU**. Notebook cells run remotely;
the PowerShell terminal stays on your laptop. Upload `catboost_workflow/source.zip` with
VS Code Explorer's **Upload to Colab** command. You already have an uploaded source ZIP
for the older workflow; upload this separate ZIP too.

Run cells in order. The first full run is validation only. It cannot submit accidentally.
For a direct comparison, retain the July 2024 cutoff and no-promotion historical features.
Previous LightGBM validation AUC was 0.686407; reported Kaggle public score was 0.5656.
We cannot infer why those differ without auditing the exact submitted CSV.

In [3]:
import platform, subprocess

assert platform.system() == "Linux", "Select the remote Colab kernel, not local Windows Python"
subprocess.run(["nvidia-smi"], check=True)
print("Run cells in this remote notebook; local PowerShell does not use this GPU.")

Run cells in this remote notebook; local PowerShell does not use this GPU.

In [4]:
from pathlib import Path
import hashlib, os, subprocess, sys, zipfile

SOURCE_ZIP = Path("/content/source.zip")  # Change if Colab Contents shows another path.
if not SOURCE_ZIP.is_file():
    raise FileNotFoundError(f"Upload catboost_workflow/source.zip to Colab, then set SOURCE_ZIP. Missing: {SOURCE_ZIP}")
digest = hashlib.sha256(SOURCE_ZIP.read_bytes()).hexdigest()
REPO = Path(f"/content/OptimlCatBoost_{digest[:10]}")
marker = REPO / ".source_zip.sha256"
if REPO.exists():
    if not marker.exists() or marker.read_text() != digest:
        raise RuntimeError("Source changed: choose a fresh REPO path or restart the Colab runtime before extracting.")
else:
    REPO.mkdir(parents=True)
    with zipfile.ZipFile(SOURCE_ZIP) as archive:
        for item in archive.infolist():
            if not (REPO / item.filename).resolve().is_relative_to(REPO.resolve()):
                raise ValueError("Unsafe ZIP path")
        archive.extractall(REPO)
    marker.write_text(digest)
assert (REPO / "optiml/gpu_check.py").is_file()
os.chdir(REPO)
print("CatBoost source ready:", REPO)

CatBoost source ready: /content/OptimlCatBoost_53e064c286

## Install and verify CatBoost GPU

This installs CatBoost and the data libraries. It does not install or compile LightGBM.
The preflight trains a tiny CatBoost model on the selected GPU and fails if the GPU is unavailable.

In [5]:
subprocess.run([sys.executable, "-m", "pip", "install", "-q", "-r", str(REPO / "catboost_workflow/requirements.txt")], check=True)
subprocess.run([sys.executable, "-m", "optiml.gpu_check", "--model", "catboost", "--device", "GPU"], cwd=REPO, check=True)

CompletedProcess(args=['/usr/bin/python3', '-m', 'optiml.gpu_check', '--model', 'catboost', '--device', 'GPU'], returncode=0)

## Mount Drive and prepare the seven competition CSVs

Keep the original CSVs in `MyDrive/OptimlData`. Preparation runs once per Colab runtime.
CatBoost runs back up to `MyDrive/OptimlRuns/CatBoost/jay`, separate from other models.

In [6]:
from pathlib import Path
from datetime import datetime, timezone
import os, sys, subprocess, shutil, json, uuid
from google.colab import drive

if "REPO" not in globals():
    raise RuntimeError("Run the source setup cell first")
os.chdir(REPO)
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))
drive.mount("/content/drive")
DRIVE_DATA = Path("/content/drive/MyDrive/OptimlData")
DATA = Path("/content/optiml_data")
PREPARED = Path("/content/optiml_prepared/catboost-baseline-v1")
OWNER = "jay"
DRIVE_RUNS = Path("/content/drive/MyDrive/OptimlRuns/CatBoost") / OWNER
DATA.mkdir(parents=True, exist_ok=True)
DRIVE_RUNS.mkdir(parents=True, exist_ok=True)
NAMES = ["train", "test", "customers", "products", "stores", "calendar", "sample_submission"]
for name in NAMES:
    source = DRIVE_DATA / f"{name}.csv"
    if not source.is_file():
        raise FileNotFoundError(f"Missing {source}; place all seven original CSVs in DRIVE_DATA")
    shutil.copy2(source, DATA / source.name)
print("Local CSVs ready:", DATA)

Mounted at /content/drive
Local CSVs ready: /content/optiml_data

In [7]:
from optiml.prepare import sha256

feature_source_hash = sha256(REPO / "optiml/features.py")
cache_manifest = PREPARED / "manifest.json"
cache_code = PREPARED / "feature_source.sha256"
if cache_manifest.exists():
    manifest = json.loads(cache_manifest.read_text())
    current = {name: sha256(DATA / f"{name}.csv") for name in NAMES}
    if manifest["source_sha256"] != current or not cache_code.exists() or cache_code.read_text() != feature_source_hash:
        raise ValueError("Data/features changed: choose a new PREPARED path and rerun preparation")
    print("Using matching completed cache:", PREPARED)
else:
    subprocess.run([sys.executable, "-m", "optiml.prepare", "--data-dir", str(DATA),
                    "--output-dir", str(PREPARED)], cwd=REPO, check=True)
    cache_code.write_text(feature_source_hash)

## Audit the earlier public-score submission when its exact CSV is available

This optional audit checks alignment against the prior run. A leaderboard gap has no known
cause until the submitted file and its generating run are compared.

In [9]:
PREVIOUS_RUN = None  # Example: Path("/content/drive/MyDrive/OptimlRuns/jay/<your_final_run>")
SUBMITTED_CSV = None # Path to the exact CSV used for the 0.5656 Kaggle submission.
if PREVIOUS_RUN is not None and SUBMITTED_CSV is not None:
    subprocess.run([sys.executable, "-m", "optiml.audit_submission", "--csv", str(SUBMITTED_CSV),
                    "--run-dir", str(PREVIOUS_RUN), "--sample", str(DATA / "sample_submission.csv")], cwd=REPO, check=True)
else:
    print("Audit pending: set PREVIOUS_RUN and SUBMITTED_CSV when available.")

Audit pending: set PREVIOUS_RUN and SUBMITTED_CSV when available.

## CatBoost experiment runner

Every fit explicitly requests GPU. Logs and results are backed up to Drive. Full validation
runs use the same held-out order lines, allowing an ID-hash check across configurations.

In [9]:
def run_catboost(label, extra_args):
    model, device = "catboost", "GPU"
    subprocess.run([sys.executable, "-m", "optiml.gpu_check", "--model", model, "--device", device], cwd=REPO, check=True)
    run_id = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + label + "_" + uuid.uuid4().hex[:8]
    local = Path("/content/optiml_gpu_runs") / OWNER / run_id
    local.parent.mkdir(parents=True, exist_ok=True)
    backup = DRIVE_RUNS / run_id
    log_path = local.parent / (run_id + ".log")
    command = [sys.executable, "-u", "-m", "optiml.train", "--prepared-dir", str(PREPARED),
               "--output-dir", str(local), "--model", model, "--device", device,
               "--threads", "2", *extra_args]
    print("Running:", " ".join(command), flush=True)
    process = None
    try:
        with log_path.open("w") as log:
            process = subprocess.Popen(command, cwd=REPO, stdout=subprocess.PIPE,
                                       stderr=subprocess.STDOUT, text=True, bufsize=1)
            for line in process.stdout:
                print(line, end="", flush=True)
                log.write(line)
                log.flush()
            if process.wait() != 0:
                raise subprocess.CalledProcessError(process.returncode, command)
    finally:
        if process is not None and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
        if local.exists():
            shutil.copy2(log_path, local / "train.log")
            shutil.copytree(local, backup, dirs_exist_ok=True)
        print("Backup location:", backup)
    return local

## Smoke test

This uses 3% of complete orders to check the full pipeline. Its AUC is not comparable to
the full-data baseline.

In [11]:
smoke = run_catboost("smoke", ["--iterations", "30", "--patience", "10", "--sample-order-fraction", "0.03"])

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T183753Z_smoke_00dd2c92 --model catboost --device GPU --threads 2 --iterations 30 --patience 10 --sample-order-fraction 0.03
Loading prepared training features...
Fit 31,352 rows; validate 9,872 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.5583287	best: 0.5583287 (0)	total: 21.5ms	remaining: 623ms
29:	test: 0.6345798	best: 0.6345798 (29)	total: 385ms	remaining: 0us
bestTest = 0.6345798075
bestIteration = 29
{
  "auc": 0.6345799463266852,
  "log_loss": 0.4763081633664319,
  "fit_rows": 31352,
  "validation_rows": 9872,
  "fit_positive_rate": 0.184071191630518,
  "validation_positive_rate": 0.1867909238249595,
  "fit_ids_sha256": "65f92e190ed263a15dbf20a678c956af74451a5a71d1c9d8f087c1dec2dd8462",
  "validation_ids_sha256": "ac62a137a2bd552f044cc29e9b7eba9480b8676f17d4afdbf7be41df41ccb0a4",
  "monthly_auc": {
    "2024-07": {
      "rows": 1685,
      "positives": 359,
      "auc": 0.6260204103068268
    },
    "2024-08": {
      "rows": 1325,
      "positives": 268,
      "auc": 0.6256195371298663
    },
    "2024-09": {
      "rows": 1388,
      "positives": 258,
      "auc": 0.618340536461549
    },
    "2024-10": {
      "rows": 1843,
      "positives": 341,
      "auc": 0.6326305883455491
    },
    "2024-11": {
      "rows": 1707,
      "positives": 275,
      "auc": 0.6478593194514982
    },
    "2024-12": {
      "rows": 1923,
      "positives": 343,
      "auc": 0.6536221721961841
    },
    "2025-01": {
      "rows": 1,
      "positives": 0,
      "auc": null
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 691,
      "positives": 118,
      "auc": 0.5918005146863076
    },
    "channel_marketplace": {
      "rows": 3477,
      "positives": 785,
      "auc": 0.6066964158961207
    },
    "channel_online": {
      "rows": 5647,
      "positives": 931,
      "auc": 0.6423474170704844
    },
    "channel_store": {
      "rows": 57,
      "positives": 10,
      "auc": 0.6000000000000001
    },
    "unseen_customer": {
      "rows": 6947,
      "positives": 1434,
      "auc": 0.6343366547587154
    },
    "seen_customer": {
      "rows": 2925,
      "positives": 410,
      "auc": 0.6003515492411385
    }
  },
  "best_iterations": 30,
  "sample_order_fraction": 0.03,
  "validation_elapsed_seconds": 12.120100086999969
}
Run complete: /content/optiml_gpu_runs/jay/20261013T183753Z_smoke_00dd2c92
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T183753Z_smoke_00dd2c92

## Full-data CatBoost baseline

Start here after the smoke test. Keep promotion excluded and history enabled, matching the
reported LightGBM baseline. This validates only; it does not produce a Kaggle CSV.

In [12]:
common = ["--cutoff", "2024-07-01", "--iterations", "2000", "--patience", "150"]
cb_baseline = run_catboost("baseline_depth6", common + ["--depth", "6"])
baseline_metrics = json.loads((cb_baseline / "metrics.json").read_text())
print("CatBoost validation AUC:", baseline_metrics["auc"])
print("Validation ID hash:", baseline_metrics["validation_ids_sha256"])

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T183811Z_baseline_depth6_c58e08f7 --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --iterations 2000 --patience 150 --depth 6
Loading prepared training features...
Fit 1,048,082 rows; validate 351,923 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6350464	best: 0.6350464 (0)	total: 157ms	remaining: 5m 14s
100:	test: 0.6825500	best: 0.6825500 (100)	total: 3.88s	remaining: 1m 12s
200:	test: 0.6885660	best: 0.6885660 (200)	total: 7.85s	remaining: 1m 10s
300:	test: 0.6921570	best: 0.6921570 (300)	total: 12.7s	remaining: 1m 11s
400:	test: 0.6940526	best: 0.6941180 (377)	total: 16.2s	remaining: 1m 4s
500:	test: 0.6952001	best: 0.6952020 (499)	total: 19.7s	remaining: 59s
600:	test: 0.6955687	best: 0.6958714 (576)	total: 24.1s	remaining: 56s
700:	test: 0.6961936	best: 0.6961936 (700)	total: 28.3s	remaining: 52.4s
800:	test: 0.6967837	best: 0.6967843 (799)	total: 31.7s	remaining: 47.5s
900:	test: 0.6971747	best: 0.6971754 (899)	total: 35.2s	remaining: 42.9s
1000:	test: 0.6980260	best: 0.6980475 (997)	total: 40.3s	remaining: 40.2s
1100:	test: 0.7006710	best: 0.7006770 (1099)	total: 43.8s	remaining: 35.7s
1200:	test: 0.7009864	best: 0.7011091 (1187)	total: 47.2s	remaining: 31.4s
1300:	test: 0.7032529	best: 0.7032680 (1297)	total: 50.9s	remaining: 27.4s
1400:	test: 0.7033470	best: 0.7033470 (1400)	total: 55.9s	remaining: 23.9s
1500:	test: 0.7035492	best: 0.7035508 (1499)	total: 59.3s	remaining: 19.7s
1600:	test: 0.7036155	best: 0.7036179 (1558)	total: 1m 2s	remaining: 15.7s
1700:	test: 0.7036295	best: 0.7036295 (1700)	total: 1m 7s	remaining: 11.8s
1800:	test: 0.7036168	best: 0.7036425 (1757)	total: 1m 11s	remaining: 7.9s
1900:	test: 0.7036347	best: 0.7036425 (1757)	total: 1m 15s	remaining: 3.91s
bestTest = 0.7036424577
bestIteration = 1757
Shrink model to first 1758 iterations.
{
  "auc": 0.7036424580146621,
  "log_loss": 0.43152344273562054,
  "fit_rows": 1048082,
  "validation_rows": 351923,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.181082225373164,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "a7db43e1a1fecd83be16f9370da3cc72b5d2639864c91ecce5f512a3e7d8e711",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.7088158598393853
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.7094583064666898
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6935106937888262
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6991363901040796
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.7072911208474817
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.7051824186176068
    },
    "2025-01": {
      "rows": 14,
      "positives": 2,
      "auc": 0.7083333333333334
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6342713377129009
    },
    "channel_marketplace": {
      "rows": 109469,
      "positives": 23768,
      "auc": 0.6853198211446997
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7137253408807148
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6185654674413787
    },
    "unseen_customer": {
      "rows": 67574,
      "positives": 15607,
      "auc": 0.6870721945273812
    },
    "seen_customer": {
      "rows": 284349,
      "positives": 48120,
      "auc": 0.702711176265495
    }
  },
  "best_iterations": 1758,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 133.72535881800002
}
Run complete: /content/optiml_gpu_runs/jay/20261013T183811Z_baseline_depth6_c58e08f7
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T183811Z_baseline_depth6_c58e08f7
CatBoost validation AUC: 0.7036424580146621
Validation ID hash: a7db43e1a1fecd83be16f9370da3cc72b5d2639864c91ecce5f512a3e7d8e711

## Compare focused CatBoost trials

After baseline, set `RUN_TRIALS=True`. Run one GPU fit at a time. Depth 5 tests lower
capacity; depth 8 tests higher capacity; the 12-month window tests recency; dropping raw
entity IDs tests whether memorization is hurting future generalization. Keep the July
validation ID hash identical. Compare October–December AUC, not only the aggregate.

In [13]:
RUN_TRIALS = False
TRIALS = {
    "depth5": ["--depth", "5"],
    "depth8": ["--depth", "8"],
    "last12m": ["--depth", "6", "--train-months", "12"],
    "no_raw_ids": ["--depth", "6", "--drop-features", "customer_id", "product_id", "store_id"],
}
run_paths = {"baseline_depth6": cb_baseline}
trial_specs = {"baseline_depth6": ["--depth", "6"]}
if RUN_TRIALS:
    for name, flags in TRIALS.items():
        run_paths[name] = run_catboost(name, common + flags)
        trial_specs[name] = flags
else:
    print("Review the baseline first, then set RUN_TRIALS=True.")

Review the baseline first, then set RUN_TRIALS=True.

In [14]:
import pandas as pd

results = {name: json.loads((path / "metrics.json").read_text()) for name, path in run_paths.items()}
assert len({m["validation_ids_sha256"] for m in results.values()}) == 1
summary = pd.DataFrame({name: {"auc": m["auc"], "best_iterations": m["best_iterations"],
                               "seconds": m["validation_elapsed_seconds"]}
                        for name, m in results.items()}).T.sort_values("auc", ascending=False)
monthly = pd.DataFrame({name: {month: row["auc"] for month, row in m["monthly_auc"].items()
                               if row["rows"] >= 1000} for name, m in results.items()})
display(summary)
display(monthly)
display(pd.DataFrame(results["baseline_depth6"]["cohorts"]).T)
summary.to_csv(DRIVE_RUNS / (cb_baseline.name + "_comparison.csv"))

                      auc  best_iterations     seconds
baseline_depth6  0.703642           1758.0  133.725359

         baseline_depth6
2024-07         0.708816
2024-08         0.709458
2024-09         0.693511
2024-10         0.699136
2024-11         0.707291
2024-12         0.705182

                         rows  positives       auc
channel_catalog       24801.0     4660.0  0.634271
channel_marketplace  109469.0    23768.0  0.685320
channel_online       215805.0    34964.0  0.713725
channel_store          1848.0      335.0  0.618565
unseen_customer       67574.0    15607.0  0.687072
seen_customer        284349.0    48120.0  0.702711

## Check recent months for shortlisted models

After comparing July validation, enable this for the best one or two configurations.
It checks drift with an October 2024 cutoff; it is not an independent test set.

In [20]:
RUN_RECENT_CHECK = False
SHORTLIST = summary.index[:2].tolist()
recent_paths = {}
if RUN_RECENT_CHECK:
    for name in dict.fromkeys(["baseline_depth6", *SHORTLIST]):
        recent_paths[name] = run_catboost(name + "_october", ["--cutoff", "2024-10-01", "--iterations", "2000", "--patience", "150"] + trial_specs[name])
    recent_metrics = {name: json.loads((path / "metrics.json").read_text()) for name, path in recent_paths.items()}
    assert len({m["validation_ids_sha256"] for m in recent_metrics.values()}) == 1
    display(pd.DataFrame({name: {"auc": m["auc"], "best_iterations": m["best_iterations"]}
                          for name, m in recent_metrics.items()}).T)

## Recovery diagnostic after a weak leaderboard score

Run this only when temporal validation and Kaggle disagree sharply. It compares the same
three feature policies on two fixed six-month forecast blocks. The stable policy removes
target history and high-cardinality entity identifiers/proxies. Select a policy for another
submission only when it behaves consistently on both blocks; do not optimize another deep
tree configuration against the July block.

In [21]:
RUN_ROLLING_DIAGNOSTIC = True
ROLLING_FOLDS = {
    "jan2024": "2024-01-01",
    "jul2024": "2024-07-01",
}
ROBUST_POLICIES = {
    "entity_history": ["--depth", "5"],
    "no_history": ["--depth", "5", "--no-history"],
    "stable_core": ["--depth", "5", "--no-history", "--drop-features",
                    "customer_id", "product_id", "store_id",
                    "product_supplier_code", "banner_id"],
}
rolling_paths = {}
if RUN_ROLLING_DIAGNOSTIC:
    for fold, cutoff in ROLLING_FOLDS.items():
        for policy, flags in ROBUST_POLICIES.items():
            name = f"{fold}_{policy}"
            rolling_paths[name] = run_catboost(
                name,
                ["--cutoff", cutoff, "--validation-months", "6",
                 "--iterations", "3000", "--patience", "200", *flags],
            )
else:
    print("Set RUN_ROLLING_DIAGNOSTIC=True after recording a weak leaderboard result.")

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T184307Z_jan2024_entity_history_5fbb5c09 --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 3000 --patience 200 --depth 5
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6423150	best: 0.6423150 (0)	total: 99.3ms	remaining: 4m 57s
100:	test: 0.6888583	best: 0.6888583 (100)	total: 4.01s	remaining: 1m 55s
200:	test: 0.6919983	best: 0.6920506 (185)	total: 6.31s	remaining: 1m 27s
300:	test: 0.6928326	best: 0.6932839 (246)	total: 8.62s	remaining: 1m 17s
400:	test: 0.6934900	best: 0.6934900 (400)	total: 10.9s	remaining: 1m 10s
500:	test: 0.6940462	best: 0.6940462 (500)	total: 13.1s	remaining: 1m 5s
600:	test: 0.6951021	best: 0.6951057 (598)	total: 17.3s	remaining: 1m 8s
700:	test: 0.6950514	best: 0.6951524 (612)	total: 19.9s	remaining: 1m 5s
800:	test: 0.6958822	best: 0.6958947 (798)	total: 22.1s	remaining: 1m
900:	test: 0.6963466	best: 0.6963549 (899)	total: 24.3s	remaining: 56.7s
1000:	test: 0.6967351	best: 0.6967422 (991)	total: 26.6s	remaining: 53s
1100:	test: 0.6969271	best: 0.6969271 (1100)	total: 29.5s	remaining: 50.8s
1200:	test: 0.6972289	best: 0.6972289 (1200)	total: 33.2s	remaining: 49.7s
1300:	test: 0.6972775	best: 0.6973432 (1271)	total: 35.4s	remaining: 46.2s
1400:	test: 0.6975690	best: 0.6975690 (1400)	total: 37.6s	remaining: 43s
1500:	test: 0.6977808	best: 0.6978264 (1491)	total: 39.9s	remaining: 39.8s
1600:	test: 0.6976458	best: 0.6978264 (1491)	total: 42.2s	remaining: 36.8s
1700:	test: 0.6978937	best: 0.6979097 (1677)	total: 46.3s	remaining: 35.3s
1800:	test: 0.6979768	best: 0.6979835 (1788)	total: 48.9s	remaining: 32.5s
1900:	test: 0.6981036	best: 0.6981037 (1898)	total: 51.1s	remaining: 29.6s
2000:	test: 0.6982543	best: 0.6982546 (1989)	total: 53.4s	remaining: 26.7s
2100:	test: 0.6979938	best: 0.6983235 (2048)	total: 55.7s	remaining: 23.8s
2200:	test: 0.6976510	best: 0.6983235 (2048)	total: 58.6s	remaining: 21.3s
bestTest = 0.6983234584
bestIteration = 2048
Shrink model to first 2049 iterations.
{
  "auc": 0.698323451375142,
  "log_loss": 0.433533450323901,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.6981396544308978
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.6968072304249859
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.7013032018382188
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.6991336513246107
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.6975901917509952
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.70046896332696
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6263772376980046
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6798180609778716
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.6996185101516363
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.6291638591762824
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.6821339547570636
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6928861373721604
    }
  },
  "best_iterations": 2049,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 103.73428174299988
}
Run complete: /content/optiml_gpu_runs/jay/20261013T184307Z_jan2024_entity_history_5fbb5c09
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T184307Z_jan2024_entity_history_5fbb5c09
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T184457Z_jan2024_no_history_f192c353 --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 3000 --patience 200 --depth 5 --no-history
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6264287	best: 0.6264287 (0)	total: 43.3ms	remaining: 2m 9s
100:	test: 0.6884117	best: 0.6884120 (99)	total: 2.42s	remaining: 1m 9s
200:	test: 0.6912495	best: 0.6913683 (193)	total: 4.66s	remaining: 1m 4s
300:	test: 0.6924798	best: 0.6924966 (299)	total: 7s	remaining: 1m 2s
400:	test: 0.6938705	best: 0.6943149 (391)	total: 10.6s	remaining: 1m 8s
500:	test: 0.6935890	best: 0.6943149 (391)	total: 13.6s	remaining: 1m 8s
bestTest = 0.6943149269
bestIteration = 391
Shrink model to first 392 iterations.
{
  "auc": 0.6943149318864482,
  "log_loss": 0.43562022965768293,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.6941079135135394
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.6931066281320184
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.6981865975507064
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.6942477501428405
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.6929247384999895
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.6963277059954086
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6215351625061692
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6738923273563632
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.6967814955666307
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.631859049945254
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.677428568127967
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6894142303784944
    }
  },
  "best_iterations": 392,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 54.3270438579998
}
Run complete: /content/optiml_gpu_runs/jay/20261013T184457Z_jan2024_no_history_f192c353
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T184457Z_jan2024_no_history_f192c353
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T184559Z_jan2024_stable_core_f32ab02e --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 3000 --patience 200 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6048804	best: 0.6048804 (0)	total: 44.9ms	remaining: 2m 14s
100:	test: 0.6576492	best: 0.6576492 (100)	total: 2.46s	remaining: 1m 10s
200:	test: 0.6617734	best: 0.6618159 (164)	total: 4.72s	remaining: 1m 5s
300:	test: 0.6642065	best: 0.6642065 (300)	total: 6.96s	remaining: 1m 2s
400:	test: 0.6669030	best: 0.6669030 (400)	total: 9.44s	remaining: 1m 1s
500:	test: 0.6682813	best: 0.6682813 (500)	total: 13.6s	remaining: 1m 7s
600:	test: 0.6691370	best: 0.6691370 (600)	total: 15.8s	remaining: 1m 3s
700:	test: 0.6700610	best: 0.6700610 (700)	total: 18.1s	remaining: 59.2s
800:	test: 0.6706753	best: 0.6706753 (800)	total: 20.3s	remaining: 55.7s
900:	test: 0.6714221	best: 0.6714223 (899)	total: 22.5s	remaining: 52.5s
1000:	test: 0.6718288	best: 0.6718288 (1000)	total: 26.3s	remaining: 52.4s
1100:	test: 0.6727977	best: 0.6728366 (1099)	total: 29.2s	remaining: 50.3s
1200:	test: 0.6730773	best: 0.6730773 (1200)	total: 31.4s	remaining: 47.1s
1300:	test: 0.6733163	best: 0.6733181 (1298)	total: 33.6s	remaining: 43.9s
1400:	test: 0.6735508	best: 0.6735551 (1388)	total: 35.8s	remaining: 40.9s
1500:	test: 0.6737705	best: 0.6737705 (1500)	total: 38.3s	remaining: 38.2s
1600:	test: 0.6739245	best: 0.6739252 (1598)	total: 42.4s	remaining: 37s
1700:	test: 0.6741520	best: 0.6741584 (1698)	total: 44.6s	remaining: 34s
1800:	test: 0.6742704	best: 0.6743154 (1757)	total: 46.8s	remaining: 31.2s
1900:	test: 0.6744500	best: 0.6744508 (1899)	total: 49.1s	remaining: 28.4s
2000:	test: 0.6744427	best: 0.6745107 (1979)	total: 51.3s	remaining: 25.6s
2100:	test: 0.6747283	best: 0.6747347 (2096)	total: 54.4s	remaining: 23.3s
2200:	test: 0.6748426	best: 0.6748426 (2200)	total: 57.8s	remaining: 21s
2300:	test: 0.6750943	best: 0.6750982 (2298)	total: 1m	remaining: 18.2s
2400:	test: 0.6750486	best: 0.6751451 (2328)	total: 1m 2s	remaining: 15.5s
2500:	test: 0.6753711	best: 0.6753727 (2498)	total: 1m 4s	remaining: 12.8s
2600:	test: 0.6753655	best: 0.6754399 (2547)	total: 1m 6s	remaining: 10.2s
2700:	test: 0.6755118	best: 0.6755139 (2699)	total: 1m 10s	remaining: 7.81s
2800:	test: 0.6755252	best: 0.6755609 (2772)	total: 1m 13s	remaining: 5.19s
2900:	test: 0.6754529	best: 0.6756015 (2867)	total: 1m 15s	remaining: 2.57s
2999:	test: 0.6754384	best: 0.6756015 (2867)	total: 1m 17s	remaining: 0us
bestTest = 0.6756015122
bestIteration = 2867
Shrink model to first 2868 iterations.
{
  "auc": 0.6756015138233671,
  "log_loss": 0.44321935849824495,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.6730413249831971
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.6778053797982042
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.6731493926176451
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.679082887215569
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.678140766541454
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.6810239296469274
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6046872246726425
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6543562419940336
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.6755399322793725
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.6065091664561049
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.662341331634078
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6684561456645264
    }
  },
  "best_iterations": 2868,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 111.7457834710001
}
Run complete: /content/optiml_gpu_runs/jay/20261013T184559Z_jan2024_stable_core_f32ab02e
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T184559Z_jan2024_stable_core_f32ab02e
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T184759Z_jul2024_entity_history_f076580e --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 3000 --patience 200 --depth 5
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6343041	best: 0.6343041 (0)	total: 80.8ms	remaining: 4m 2s
100:	test: 0.6802592	best: 0.6802592 (100)	total: 3.59s	remaining: 1m 42s
200:	test: 0.6867942	best: 0.6867942 (200)	total: 6.81s	remaining: 1m 34s
300:	test: 0.6902680	best: 0.6902680 (300)	total: 10s	remaining: 1m 29s
400:	test: 0.6928685	best: 0.6928734 (397)	total: 14.9s	remaining: 1m 36s
500:	test: 0.6949861	best: 0.6949881 (499)	total: 18.1s	remaining: 1m 30s
600:	test: 0.6957255	best: 0.6957347 (599)	total: 21.2s	remaining: 1m 24s
700:	test: 0.6964683	best: 0.6964691 (698)	total: 24.4s	remaining: 1m 19s
800:	test: 0.6973913	best: 0.6973913 (800)	total: 29.3s	remaining: 1m 20s
900:	test: 0.6984501	best: 0.6984501 (900)	total: 32.4s	remaining: 1m 15s
1000:	test: 0.6989312	best: 0.6989908 (997)	total: 35.6s	remaining: 1m 11s
1100:	test: 0.7017594	best: 0.7017682 (1097)	total: 38.7s	remaining: 1m 6s
1200:	test: 0.7017914	best: 0.7019991 (1189)	total: 43.5s	remaining: 1m 5s
1300:	test: 0.7040280	best: 0.7040332 (1298)	total: 46.6s	remaining: 1m
1400:	test: 0.7060712	best: 0.7060722 (1398)	total: 49.8s	remaining: 56.8s
1500:	test: 0.7062003	best: 0.7062044 (1497)	total: 52.9s	remaining: 52.9s
1600:	test: 0.7063082	best: 0.7063201 (1586)	total: 57.6s	remaining: 50.3s
1700:	test: 0.7066875	best: 0.7066894 (1699)	total: 1m	remaining: 46.5s
1800:	test: 0.7067381	best: 0.7067480 (1793)	total: 1m 4s	remaining: 42.6s
1900:	test: 0.7069348	best: 0.7069364 (1899)	total: 1m 7s	remaining: 38.8s
2000:	test: 0.7072448	best: 0.7072678 (1976)	total: 1m 12s	remaining: 36s
2100:	test: 0.7073106	best: 0.7073106 (2100)	total: 1m 15s	remaining: 32.2s
2200:	test: 0.7075051	best: 0.7075177 (2195)	total: 1m 18s	remaining: 28.5s
2300:	test: 0.7075723	best: 0.7075746 (2296)	total: 1m 21s	remaining: 24.8s
2400:	test: 0.7076518	best: 0.7076552 (2398)	total: 1m 25s	remaining: 21.4s
2500:	test: 0.7076582	best: 0.7076918 (2454)	total: 1m 29s	remaining: 17.8s
2600:	test: 0.7077132	best: 0.7077142 (2599)	total: 1m 32s	remaining: 14.2s
2700:	test: 0.7077537	best: 0.7077621 (2658)	total: 1m 35s	remaining: 10.6s
2800:	test: 0.7077584	best: 0.7077852 (2730)	total: 1m 39s	remaining: 7.1s
2900:	test: 0.7077771	best: 0.7077852 (2730)	total: 1m 43s	remaining: 3.53s
bestTest = 0.7077851593
bestIteration = 2730
Shrink model to first 2731 iterations.
{
  "auc": 0.7077851924232139,
  "log_loss": 0.42982092032804065,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.711616656915531
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.7144742571452555
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6993404159669029
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.7044956069170579
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.7111052247370092
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.7067412947272256
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6364388358211945
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.6880357338728622
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7190905235265299
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6219471051878742
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6901304672116609
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.7072789485347555
    }
  },
  "best_iterations": 2731,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 161.8348213700001
}
Run complete: /content/optiml_gpu_runs/jay/20261013T184759Z_jul2024_entity_history_f076580e
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T184759Z_jul2024_entity_history_f076580e
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T185049Z_jul2024_no_history_18b82169 --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 3000 --patience 200 --depth 5 --no-history
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6335834	best: 0.6335834 (0)	total: 55ms	remaining: 2m 44s
100:	test: 0.6811412	best: 0.6811481 (99)	total: 3.36s	remaining: 1m 36s
200:	test: 0.6875603	best: 0.6875603 (200)	total: 6.49s	remaining: 1m 30s
300:	test: 0.6915044	best: 0.6915044 (300)	total: 10.6s	remaining: 1m 35s
400:	test: 0.6932439	best: 0.6932439 (400)	total: 14.4s	remaining: 1m 33s
500:	test: 0.6945791	best: 0.6945791 (500)	total: 17.6s	remaining: 1m 27s
600:	test: 0.6959929	best: 0.6959929 (600)	total: 20.6s	remaining: 1m 22s
700:	test: 0.6962550	best: 0.6963445 (695)	total: 24.7s	remaining: 1m 21s
800:	test: 0.6971906	best: 0.6971906 (800)	total: 28.8s	remaining: 1m 18s
900:	test: 0.6976441	best: 0.6976510 (897)	total: 31.8s	remaining: 1m 14s
1000:	test: 0.7004637	best: 0.7004637 (1000)	total: 34.9s	remaining: 1m 9s
1100:	test: 0.7007249	best: 0.7007405 (1094)	total: 39s	remaining: 1m 7s
1200:	test: 0.7007973	best: 0.7010016 (1189)	total: 42.8s	remaining: 1m 4s
1300:	test: 0.7009127	best: 0.7010016 (1189)	total: 45.8s	remaining: 59.8s
1400:	test: 0.7011119	best: 0.7011119 (1399)	total: 48.9s	remaining: 55.8s
1500:	test: 0.7012961	best: 0.7012997 (1497)	total: 52.4s	remaining: 52.3s
1600:	test: 0.7014203	best: 0.7014431 (1549)	total: 56.6s	remaining: 49.5s
1700:	test: 0.7016611	best: 0.7016622 (1699)	total: 59.6s	remaining: 45.5s
1800:	test: 0.7018792	best: 0.7018827 (1799)	total: 1m 2s	remaining: 41.7s
1900:	test: 0.7020487	best: 0.7020637 (1893)	total: 1m 5s	remaining: 38.1s
2000:	test: 0.7020542	best: 0.7021056 (1972)	total: 1m 10s	remaining: 35.2s
2100:	test: 0.7021710	best: 0.7021757 (2076)	total: 1m 13s	remaining: 31.5s
2200:	test: 0.7021926	best: 0.7021935 (2194)	total: 1m 16s	remaining: 27.8s
2300:	test: 0.7022697	best: 0.7022755 (2296)	total: 1m 19s	remaining: 24.2s
2400:	test: 0.7023163	best: 0.7023233 (2378)	total: 1m 24s	remaining: 21.1s
2500:	test: 0.7023248	best: 0.7023623 (2425)	total: 1m 27s	remaining: 17.5s

In [22]:
if rolling_paths:
    import pandas as pd

    rolling_metrics = {
        name: json.loads((path / "metrics.json").read_text())
        for name, path in rolling_paths.items()
    }
    rolling_summary = pd.DataFrame({
        name: {
            "auc": metric["auc"],
            "best_iterations": metric["best_iterations"],
            "validation_rows": metric["validation_rows"],
        }
        for name, metric in rolling_metrics.items()
    }).T
    rolling_summary[["fold", "policy"]] = rolling_summary.index.to_series().str.split("_", n=1, expand=True)
    display(rolling_summary.sort_values(["policy", "fold"]))
    display(rolling_summary.pivot(index="policy", columns="fold", values="auc"))

,auc,best_iterations,validation_rows,fold,policy
jan2024_entity_history,0.698323,2049.0,396321.0,jan2024,entity_history
jul2024_entity_history,0.707785,2731.0,351909.0,jul2024,entity_history
jan2024_no_history,0.694315,392.0,396321.0,jan2024,no_history
jul2024_no_history,0.704869,2802.0,351909.0,jul2024,no_history
jan2024_stable_core,0.675602,2868.0,396321.0,jan2024,stable_core
jul2024_stable_core,0.689663,2970.0,351909.0,jul2024,stable_core

fold             jan2024   jul2024
policy
entity_history  0.698323  0.707785
no_history      0.694315  0.704869
stable_core     0.675602  0.689663

In [23]:
stable_final = run_catboost(
    "stable_core_final",
    [
        "--cutoff", "2024-07-01",
        "--validation-months", "6",
        "--iterations", "5000",
        "--patience", "300",
        "--depth", "5",
        "--no-history",
        "--drop-features",
        "customer_id",
        "product_id",
        "store_id",
        "product_supplier_code",
        "banner_id",
        "--finalize",
    ],
)

subprocess.run(
    [
        sys.executable,
        "-m",
        "optiml.audit_submission",
        "--csv", str(stable_final / "submission.csv"),
        "--run-dir", str(stable_final),
        "--sample", str(DATA / "sample_submission.csv"),
    ],
    cwd=REPO,
    check=True,
)

stable_metrics = json.loads((stable_final / "metrics.json").read_text())

print("Validation AUC:", stable_metrics["auc"])
print("Best iterations:", stable_metrics["best_iterations"])
print("Submission:", DRIVE_RUNS / stable_final.name / "submission.csv")

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T185758Z_stable_core_final_a9c89e5f --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id --finalize
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6067169	best: 0.6067169 (0)	total: 50.3ms	remaining: 4m 11s
100:	test: 0.6513993	best: 0.6513993 (100)	total: 3.54s	remaining: 2m 51s
200:	test: 0.6589505	best: 0.6589505 (200)	total: 8s	remaining: 3m 10s
300:	test: 0.6632290	best: 0.6632290 (300)	total: 11.1s	remaining: 2m 52s
400:	test: 0.6655160	best: 0.6655160 (400)	total: 14.1s	remaining: 2m 41s
500:	test: 0.6668046	best: 0.6668046 (500)	total: 17.1s	remaining: 2m 33s
600:	test: 0.6728362	best: 0.6728376 (599)	total: 22s	remaining: 2m 40s
700:	test: 0.6744047	best: 0.6744159 (692)	total: 25s	remaining: 2m 33s
800:	test: 0.6758428	best: 0.6758442 (799)	total: 28s	remaining: 2m 27s
900:	test: 0.6763152	best: 0.6764058 (893)	total: 31s	remaining: 2m 21s
1000:	test: 0.6766727	best: 0.6766738 (998)	total: 35.3s	remaining: 2m 21s
1100:	test: 0.6775044	best: 0.6775064 (1099)	total: 38.7s	remaining: 2m 17s
1200:	test: 0.6776263	best: 0.6778980 (1189)	total: 41.7s	remaining: 2m 11s
1300:	test: 0.6779566	best: 0.6779566 (1300)	total: 44.7s	remaining: 2m 6s
1400:	test: 0.6785021	best: 0.6785021 (1400)	total: 48.6s	remaining: 2m 4s
1500:	test: 0.6791430	best: 0.6791466 (1497)	total: 52.5s	remaining: 2m 2s
1600:	test: 0.6791936	best: 0.6792069 (1513)	total: 55.5s	remaining: 1m 57s
1700:	test: 0.6792736	best: 0.6792753 (1699)	total: 58.6s	remaining: 1m 53s
1800:	test: 0.6796563	best: 0.6796662 (1792)	total: 1m 1s	remaining: 1m 49s
1900:	test: 0.6822257	best: 0.6823833 (1883)	total: 1m 6s	remaining: 1m 48s
2000:	test: 0.6848037	best: 0.6848037 (2000)	total: 1m 9s	remaining: 1m 43s
2100:	test: 0.6849529	best: 0.6849535 (2099)	total: 1m 12s	remaining: 1m 39s
2200:	test: 0.6850983	best: 0.6851088 (2191)	total: 1m 15s	remaining: 1m 35s
2300:	test: 0.6852530	best: 0.6852605 (2293)	total: 1m 20s	remaining: 1m 34s
2400:	test: 0.6852628	best: 0.6852925 (2380)	total: 1m 23s	remaining: 1m 30s
2500:	test: 0.6853674	best: 0.6853674 (2500)	total: 1m 26s	remaining: 1m 26s
2600:	test: 0.6854453	best: 0.6854453 (2600)	total: 1m 29s	remaining: 1m 22s
2700:	test: 0.6876347	best: 0.6876432 (2691)	total: 1m 34s	remaining: 1m 20s
2800:	test: 0.6876096	best: 0.6876618 (2726)	total: 1m 37s	remaining: 1m 16s
2900:	test: 0.6876951	best: 0.6876992 (2899)	total: 1m 40s	remaining: 1m 12s
3000:	test: 0.6895223	best: 0.6895223 (3000)	total: 1m 43s	remaining: 1m 8s
3100:	test: 0.6895781	best: 0.6895862 (3089)	total: 1m 47s	remaining: 1m 5s
3200:	test: 0.6896530	best: 0.6896530 (3200)	total: 1m 51s	remaining: 1m 2s
3300:	test: 0.6896311	best: 0.6896589 (3208)	total: 1m 54s	remaining: 58.7s
3400:	test: 0.6897023	best: 0.6897163 (3393)	total: 1m 57s	remaining: 55s
3500:	test: 0.6898049	best: 0.6898058 (3498)	total: 2m 1s	remaining: 51.9s
3600:	test: 0.6898426	best: 0.6898447 (3571)	total: 2m 4s	remaining: 48.5s
3700:	test: 0.6898968	best: 0.6898968 (3700)	total: 2m 7s	remaining: 44.9s
3800:	test: 0.6899396	best: 0.6899460 (3781)	total: 2m 10s	remaining: 41.3s
3900:	test: 0.6901362	best: 0.6901362 (3900)	total: 2m 14s	remaining: 38s
4000:	test: 0.6902274	best: 0.6902274 (4000)	total: 2m 18s	remaining: 34.6s
4100:	test: 0.6902199	best: 0.6902514 (4046)	total: 2m 21s	remaining: 31.1s
4200:	test: 0.6902134	best: 0.6902514 (4046)	total: 2m 24s	remaining: 27.5s
4300:	test: 0.6900220	best: 0.6902514 (4046)	total: 2m 28s	remaining: 24.1s
bestTest = 0.6902513802
bestIteration = 4046
Shrink model to first 4047 iterations.
{
  "auc": 0.690251336960769,
  "log_loss": 0.437747531762014,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.6927121109592327
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.6948299973387715
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6803363459856672
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6900707146396685
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.6936485295987446
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.6910853273072983
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.620393138246606
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.6692049581707308
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7018070088920451
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6079549378027247
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6751284395426288
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.6887947739217237
    }
  },
  "best_iterations": 4047,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 191.59740234799983
}
Refitting selected iteration count on labeled history...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	total: 48.4ms	remaining: 3m 15s
100:	total: 5.21s	remaining: 3m 23s
200:	total: 9.01s	remaining: 2m 52s
300:	total: 12.7s	remaining: 2m 38s
400:	total: 17.3s	remaining: 2m 37s
500:	total: 21.4s	remaining: 2m 31s
600:	total: 25.1s	remaining: 2m 24s
700:	total: 28.8s	remaining: 2m 17s
800:	total: 33.7s	remaining: 2m 16s
900:	total: 37.3s	remaining: 2m 10s
1000:	total: 40.9s	remaining: 2m 4s
1100:	total: 44.9s	remaining: 2m
1200:	total: 49.4s	remaining: 1m 56s
1300:	total: 52.9s	remaining: 1m 51s
1400:	total: 56.5s	remaining: 1m 46s
1500:	total: 1m	remaining: 1m 43s
1600:	total: 1m 4s	remaining: 1m 39s
1700:	total: 1m 8s	remaining: 1m 34s
1800:	total: 1m 12s	remaining: 1m 29s
1900:	total: 1m 16s	remaining: 1m 26s
2000:	total: 1m 20s	remaining: 1m 22s
2100:	total: 1m 24s	remaining: 1m 17s
2200:	total: 1m 27s	remaining: 1m 13s
2300:	total: 1m 32s	remaining: 1m 10s
2400:	total: 1m 35s	remaining: 1m 5s
2500:	total: 1m 39s	remaining: 1m 1s
2600:	total: 1m 44s	remaining: 58s
2700:	total: 1m 48s	remaining: 53.9s
2800:	total: 1m 51s	remaining: 49.7s
2900:	total: 1m 55s	remaining: 45.5s
3000:	total: 2m	remaining: 41.9s
3100:	total: 2m 3s	remaining: 37.8s
3200:	total: 2m 7s	remaining: 33.7s
3300:	total: 2m 11s	remaining: 29.7s
3400:	total: 2m 15s	remaining: 25.8s
3500:	total: 2m 19s	remaining: 21.7s
3600:	total: 2m 22s	remaining: 17.7s
3700:	total: 2m 27s	remaining: 13.8s
3800:	total: 2m 31s	remaining: 9.8s
3900:	total: 2m 34s	remaining: 5.8s
4000:	total: 2m 38s	remaining: 1.82s
4046:	total: 2m 40s	remaining: 0us
Run complete: /content/optiml_gpu_runs/jay/20261013T185758Z_stable_core_final_a9c89e5f
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T185758Z_stable_core_final_a9c89e5f
Validation AUC: 0.690251336960769
Best iterations: 4047
Submission: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T185758Z_stable_core_final_a9c89e5f/submission.csv

In [24]:
stable_metrics = json.loads((stable_final / "metrics.json").read_text())
stable_importance = pd.read_csv(stable_final / "feature_importance.csv")

print("Validation AUC:", stable_metrics["auc"])
print("Best iterations:", stable_metrics["best_iterations"])

display(
    stable_importance
    .sort_values("importance", ascending=False)
    .head(30)
)

display(pd.DataFrame(stable_metrics["monthly_auc"]).T)
display(pd.DataFrame(stable_metrics["cohorts"]).T)

Validation AUC: 0.690251336960769
Best iterations: 4047

                        feature  importance
0   customer_store_region_match    6.445220
1        product_packaging_type    5.493858
2    customer_newsletter_opt_in    5.313250
3                     gift_wrap    5.243466
4             product_weight_kg    4.567796
5                store_age_days    4.131277
6                  store_region    3.930757
7        customer_customer_type    3.757514
8               customer_region    3.576011
9                  store_format    3.469737
10           product_list_price    3.395435
11       freight_to_gross_ratio    3.381358
12             product_category    3.229267
13                         hour    2.244578
14                month_of_year    2.238034
15                     discount    2.059890
16         customer_tenure_days    1.834184
17               line_weight_kg    1.651065
18                 basket_lines    1.544212
19           product_volume_cm3    1.539068
20                 freight_cost    1.500129
21                   unit_price    1.491173
22       product_density_kg_cm3    1.269538
23           log1p_freight_cost    1.265929
24          price_to_list_ratio    1.149517
25                      channel    1.109598
26                          cpi    1.103168
27                temperature_f    1.085631
28                   fuel_price    0.992370
29            product_length_cm    0.976191

            rows  positives       auc
2024-07  59589.0    10757.0  0.692712
2024-08  58214.0    10560.0  0.694830
2024-09  55090.0     9937.0  0.680336
2024-10  61345.0    11256.0  0.690071
2024-11  58821.0    10517.0  0.693649
2024-12  58850.0    10698.0  0.691085

                         rows  positives       auc
channel_catalog       24801.0     4660.0  0.620393
channel_marketplace  109455.0    23766.0  0.669205
channel_online       215805.0    34964.0  0.701807
channel_store          1848.0      335.0  0.607955
unseen_customer       67564.0    15605.0  0.675128
seen_customer        284345.0    48120.0  0.688795

In [25]:
stable_drops = [
    "customer_id",
    "product_id",
    "store_id",
    "product_supplier_code",
    "banner_id",
]

macro_drops = [
    "cpi",
    "fuel_price",
    "temperature_f",
    "unemployment",
    "fuel_surcharge",
]

age_drops = [
    "customer_tenure_days",
    "customer_tenure_days_invalid",
    "store_age_days",
    "store_age_days_invalid",
]

NEXT_POLICIES = {
    "stable_depth4": [
        "--depth", "4",
        "--no-history",
        "--drop-features", *stable_drops,
    ],
    "stable_no_macro": [
        "--depth", "5",
        "--no-history",
        "--drop-features", *(stable_drops + macro_drops),
    ],
    "stable_no_macro_age": [
        "--depth", "5",
        "--no-history",
        "--drop-features", *(stable_drops + macro_drops + age_drops),
    ],
}

next_paths = {}

for fold, cutoff in {
    "jan2024": "2024-01-01",
    "jul2024": "2024-07-01",
}.items():
    for policy, flags in NEXT_POLICIES.items():
        name = f"{fold}_{policy}"
        next_paths[name] = run_catboost(
            name,
            [
                "--cutoff", cutoff,
                "--validation-months", "6",
                "--iterations", "5000",
                "--patience", "300",
                *flags,
            ],
        )

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T191424Z_jan2024_stable_depth4_97ee8773 --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 5000 --patience 300 --depth 4 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6043150	best: 0.6043150 (0)	total: 36.4ms	remaining: 3m 2s
100:	test: 0.6550145	best: 0.6550145 (100)	total: 3.44s	remaining: 2m 47s
200:	test: 0.6588566	best: 0.6601352 (197)	total: 6.47s	remaining: 2m 34s
300:	test: 0.6592746	best: 0.6601352 (197)	total: 8.46s	remaining: 2m 12s
400:	test: 0.6615199	best: 0.6615199 (400)	total: 10.4s	remaining: 1m 59s
500:	test: 0.6631044	best: 0.6631044 (500)	total: 12.4s	remaining: 1m 51s
600:	test: 0.6644608	best: 0.6645191 (591)	total: 14.3s	remaining: 1m 45s
700:	test: 0.6656893	best: 0.6656968 (698)	total: 17s	remaining: 1m 44s
800:	test: 0.6663333	best: 0.6663357 (799)	total: 20.5s	remaining: 1m 47s
900:	test: 0.6669098	best: 0.6669098 (900)	total: 22.5s	remaining: 1m 42s
1000:	test: 0.6674558	best: 0.6674589 (996)	total: 24.4s	remaining: 1m 37s
1100:	test: 0.6683906	best: 0.6683906 (1100)	total: 26.4s	remaining: 1m 33s
1200:	test: 0.6688901	best: 0.6689114 (1191)	total: 28.4s	remaining: 1m 29s
1300:	test: 0.6691327	best: 0.6691346 (1299)	total: 30.6s	remaining: 1m 26s
1400:	test: 0.6694212	best: 0.6694312 (1395)	total: 34.4s	remaining: 1m 28s
1500:	test: 0.6696244	best: 0.6696751 (1476)	total: 36.6s	remaining: 1m 25s
1600:	test: 0.6697023	best: 0.6697124 (1598)	total: 38.6s	remaining: 1m 21s
1700:	test: 0.6701589	best: 0.6701754 (1696)	total: 40.6s	remaining: 1m 18s
1800:	test: 0.6704600	best: 0.6704600 (1800)	total: 42.5s	remaining: 1m 15s
1900:	test: 0.6704545	best: 0.6705187 (1869)	total: 44.5s	remaining: 1m 12s
2000:	test: 0.6706116	best: 0.6706116 (2000)	total: 48.2s	remaining: 1m 12s
2100:	test: 0.6707504	best: 0.6708801 (2070)	total: 50.8s	remaining: 1m 10s
2200:	test: 0.6709709	best: 0.6710653 (2189)	total: 52.8s	remaining: 1m 7s
2300:	test: 0.6712444	best: 0.6712444 (2300)	total: 54.8s	remaining: 1m 4s
2400:	test: 0.6712510	best: 0.6712835 (2391)	total: 56.8s	remaining: 1m 1s
2500:	test: 0.6716174	best: 0.6716174 (2500)	total: 58.8s	remaining: 58.7s
2600:	test: 0.6719279	best: 0.6719303 (2599)	total: 1m 1s	remaining: 57.2s
2700:	test: 0.6719553	best: 0.6719589 (2605)	total: 1m 4s	remaining: 55.3s
2800:	test: 0.6720259	best: 0.6720553 (2770)	total: 1m 6s	remaining: 52.5s
2900:	test: 0.6721207	best: 0.6721382 (2889)	total: 1m 8s	remaining: 49.9s
3000:	test: 0.6721807	best: 0.6721853 (2995)	total: 1m 11s	remaining: 47.3s
3100:	test: 0.6723846	best: 0.6723897 (3090)	total: 1m 13s	remaining: 44.8s
3200:	test: 0.6723381	best: 0.6724513 (3170)	total: 1m 16s	remaining: 42.8s
3300:	test: 0.6725079	best: 0.6725079 (3300)	total: 1m 19s	remaining: 40.8s
3400:	test: 0.6725708	best: 0.6725715 (3394)	total: 1m 21s	remaining: 38.2s
3500:	test: 0.6726787	best: 0.6726787 (3500)	total: 1m 23s	remaining: 35.7s
3600:	test: 0.6726933	best: 0.6727221 (3570)	total: 1m 25s	remaining: 33.1s
3700:	test: 0.6727742	best: 0.6727806 (3698)	total: 1m 27s	remaining: 30.6s
3800:	test: 0.6728327	best: 0.6728434 (3762)	total: 1m 29s	remaining: 28.3s
3900:	test: 0.6728904	best: 0.6728940 (3894)	total: 1m 33s	remaining: 26.3s
4000:	test: 0.6729907	best: 0.6729908 (3999)	total: 1m 35s	remaining: 23.8s
4100:	test: 0.6730598	best: 0.6730598 (4100)	total: 1m 37s	remaining: 21.4s
4200:	test: 0.6730282	best: 0.6730760 (4122)	total: 1m 39s	remaining: 18.9s
4300:	test: 0.6729766	best: 0.6730760 (4122)	total: 1m 41s	remaining: 16.5s
4400:	test: 0.6730217	best: 0.6730760 (4122)	total: 1m 43s	remaining: 14.1s
4500:	test: 0.6731669	best: 0.6731705 (4498)	total: 1m 47s	remaining: 11.9s
4600:	test: 0.6732765	best: 0.6732777 (4598)	total: 1m 49s	remaining: 9.51s
4700:	test: 0.6733585	best: 0.6733585 (4700)	total: 1m 51s	remaining: 7.1s
4800:	test: 0.6734160	best: 0.6734204 (4791)	total: 1m 53s	remaining: 4.71s
4900:	test: 0.6734601	best: 0.6734621 (4897)	total: 1m 55s	remaining: 2.34s
4999:	test: 0.6735894	best: 0.6735966 (4985)	total: 1m 57s	remaining: 0us
bestTest = 0.673596561
bestIteration = 4985
Shrink model to first 4986 iterations.
{
  "auc": 0.6735966036561286,
  "log_loss": 0.44396807139787514,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.6724656811053744
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.6753327251778347
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.671060296246518
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.6775720046651672
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.6742216015608085
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.6798818403169348
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6024642664836192
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6537770443869222
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.672768198210742
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.6055247901400937
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.6607144847750849
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6661430646821799
    }
  },
  "best_iterations": 4986,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 154.67972822299998
}
Run complete: /content/optiml_gpu_runs/jay/20261013T191424Z_jan2024_stable_depth4_97ee8773
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T191424Z_jan2024_stable_depth4_97ee8773
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T191705Z_jan2024_stable_no_macro_c82dffbb --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id cpi fuel_price temperature_f unemployment fuel_surcharge
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6033966	best: 0.6033966 (0)	total: 40.1ms	remaining: 3m 20s
100:	test: 0.6582592	best: 0.6582592 (100)	total: 3.32s	remaining: 2m 40s
200:	test: 0.6644195	best: 0.6644195 (200)	total: 6.88s	remaining: 2m 44s
300:	test: 0.6672099	best: 0.6672099 (300)	total: 9.11s	remaining: 2m 22s
400:	test: 0.6684905	best: 0.6684905 (400)	total: 11.3s	remaining: 2m 10s
500:	test: 0.6694391	best: 0.6694391 (500)	total: 13.5s	remaining: 2m 1s
600:	test: 0.6702190	best: 0.6702258 (594)	total: 15.7s	remaining: 1m 55s
700:	test: 0.6703500	best: 0.6704021 (653)	total: 19.8s	remaining: 2m 1s
800:	test: 0.6708844	best: 0.6709229 (760)	total: 22.4s	remaining: 1m 57s
900:	test: 0.6712561	best: 0.6712623 (896)	total: 24.6s	remaining: 1m 51s
1000:	test: 0.6716055	best: 0.6716055 (1000)	total: 26.8s	remaining: 1m 47s
1100:	test: 0.6718649	best: 0.6718649 (1100)	total: 29s	remaining: 1m 42s
1200:	test: 0.6720372	best: 0.6720372 (1200)	total: 31.8s	remaining: 1m 40s
1300:	test: 0.6723014	best: 0.6723071 (1297)	total: 35.8s	remaining: 1m 41s
1400:	test: 0.6724180	best: 0.6724481 (1395)	total: 38s	remaining: 1m 37s
1500:	test: 0.6724996	best: 0.6725174 (1469)	total: 40.2s	remaining: 1m 33s
1600:	test: 0.6754604	best: 0.6754721 (1586)	total: 42.3s	remaining: 1m 29s
1700:	test: 0.6757023	best: 0.6757314 (1679)	total: 44.5s	remaining: 1m 26s
1800:	test: 0.6757414	best: 0.6757706 (1728)	total: 48.2s	remaining: 1m 25s
1900:	test: 0.6759076	best: 0.6759154 (1882)	total: 51.1s	remaining: 1m 23s
2000:	test: 0.6760403	best: 0.6760508 (1979)	total: 53.4s	remaining: 1m 20s
2100:	test: 0.6763576	best: 0.6763867 (2081)	total: 55.6s	remaining: 1m 16s
2200:	test: 0.6767290	best: 0.6767290 (2200)	total: 57.8s	remaining: 1m 13s
2300:	test: 0.6769657	best: 0.6769665 (2298)	total: 1m	remaining: 1m 10s
2400:	test: 0.6771435	best: 0.6771699 (2373)	total: 1m 4s	remaining: 1m 9s
2500:	test: 0.6772577	best: 0.6772577 (2499)	total: 1m 6s	remaining: 1m 6s
2600:	test: 0.6773384	best: 0.6773591 (2592)	total: 1m 8s	remaining: 1m 3s
2700:	test: 0.6775223	best: 0.6775363 (2680)	total: 1m 10s	remaining: 1m
2800:	test: 0.6774485	best: 0.6775363 (2680)	total: 1m 13s	remaining: 57.3s
2900:	test: 0.6776533	best: 0.6776533 (2900)	total: 1m 16s	remaining: 55.1s
3000:	test: 0.6777210	best: 0.6777356 (2996)	total: 1m 19s	remaining: 53s
3100:	test: 0.6777416	best: 0.6777658 (3096)	total: 1m 21s	remaining: 50.1s
3200:	test: 0.6803216	best: 0.6803375 (3188)	total: 1m 24s	remaining: 47.2s
3300:	test: 0.6803057	best: 0.6803375 (3188)	total: 1m 26s	remaining: 44.4s
3400:	test: 0.6802993	best: 0.6803375 (3188)	total: 1m 28s	remaining: 41.6s
bestTest = 0.6803374588
bestIteration = 3188
Shrink model to first 3189 iterations.
{
  "auc": 0.680337503243327,
  "log_loss": 0.44119883237609886,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.6765923526054995
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.6823197407443431
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.6813748044967358
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.6840603070322109
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.6817776116322088
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.685314976518658
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6096987080398144
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6589408449865124
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.6817707125274413
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.6092043572250765
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.6714462080665844
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6744585635241013
    }
  },
  "best_iterations": 3189,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 125.74748168899987
}
Run complete: /content/optiml_gpu_runs/jay/20261013T191705Z_jan2024_stable_no_macro_c82dffbb
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T191705Z_jan2024_stable_no_macro_c82dffbb
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57 --model catboost --device GPU --threads 2 --cutoff 2024-01-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id cpi fuel_price temperature_f unemployment fuel_surcharge customer_tenure_days customer_tenure_days_invalid store_age_days store_age_days_invalid
Loading prepared training features...
Fit 651,761 rows; validate 396,321 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6058366	best: 0.6058366 (0)	total: 40.2ms	remaining: 3m 21s
100:	test: 0.6570623	best: 0.6570623 (100)	total: 4.7s	remaining: 3m 47s
200:	test: 0.6626720	best: 0.6626720 (200)	total: 6.93s	remaining: 2m 45s
300:	test: 0.6656409	best: 0.6656409 (300)	total: 9.18s	remaining: 2m 23s
400:	test: 0.6670242	best: 0.6670242 (400)	total: 11.5s	remaining: 2m 11s
500:	test: 0.6680638	best: 0.6680654 (498)	total: 13.7s	remaining: 2m 3s
600:	test: 0.6686043	best: 0.6686076 (598)	total: 17.4s	remaining: 2m 7s
700:	test: 0.6691512	best: 0.6691512 (700)	total: 20.5s	remaining: 2m 5s
800:	test: 0.6696824	best: 0.6696953 (799)	total: 22.7s	remaining: 1m 59s
900:	test: 0.6702395	best: 0.6702423 (899)	total: 24.9s	remaining: 1m 53s
1000:	test: 0.6706669	best: 0.6706852 (989)	total: 27.1s	remaining: 1m 48s
1100:	test: 0.6739721	best: 0.6739851 (1093)	total: 29.3s	remaining: 1m 43s
1200:	test: 0.6741065	best: 0.6741065 (1200)	total: 33.6s	remaining: 1m 46s
1300:	test: 0.6769065	best: 0.6769124 (1294)	total: 35.8s	remaining: 1m 41s
1400:	test: 0.6770188	best: 0.6770306 (1370)	total: 37.9s	remaining: 1m 37s
1500:	test: 0.6769760	best: 0.6770587 (1427)	total: 40.1s	remaining: 1m 33s
1600:	test: 0.6794503	best: 0.6794858 (1569)	total: 42.3s	remaining: 1m 29s
1700:	test: 0.6795772	best: 0.6796202 (1657)	total: 45.4s	remaining: 1m 28s
1800:	test: 0.6796787	best: 0.6796849 (1758)	total: 48.8s	remaining: 1m 26s
1900:	test: 0.6797979	best: 0.6798300 (1884)	total: 51s	remaining: 1m 23s
2000:	test: 0.6798635	best: 0.6798812 (1982)	total: 53.2s	remaining: 1m 19s
2100:	test: 0.6802161	best: 0.6802344 (2092)	total: 55.4s	remaining: 1m 16s
2200:	test: 0.6806010	best: 0.6806010 (2200)	total: 57.6s	remaining: 1m 13s
2300:	test: 0.6806314	best: 0.6806374 (2283)	total: 1m 1s	remaining: 1m 12s
2400:	test: 0.6809286	best: 0.6809536 (2372)	total: 1m 4s	remaining: 1m 9s
2500:	test: 0.6809643	best: 0.6809821 (2465)	total: 1m 6s	remaining: 1m 6s
2600:	test: 0.6810578	best: 0.6810649 (2594)	total: 1m 8s	remaining: 1m 3s
2700:	test: 0.6811413	best: 0.6811573 (2697)	total: 1m 10s	remaining: 1m
2800:	test: 0.6811836	best: 0.6811965 (2779)	total: 1m 13s	remaining: 57.8s
2900:	test: 0.6812838	best: 0.6812838 (2900)	total: 1m 17s	remaining: 55.9s
3000:	test: 0.6812658	best: 0.6813228 (2940)	total: 1m 19s	remaining: 52.9s
3100:	test: 0.6813504	best: 0.6813843 (3025)	total: 1m 21s	remaining: 50s
3200:	test: 0.6813162	best: 0.6813843 (3025)	total: 1m 23s	remaining: 47.1s
3300:	test: 0.6813419	best: 0.6813843 (3025)	total: 1m 25s	remaining: 44.2s
bestTest = 0.6813842952
bestIteration = 3025
Shrink model to first 3026 iterations.
{
  "auc": 0.681384262282076,
  "log_loss": 0.44060857765382166,
  "fit_rows": 651761,
  "validation_rows": 396321,
  "fit_positive_rate": 0.18013198089483723,
  "validation_positive_rate": 0.18067929784190087,
  "fit_ids_sha256": "4e9d4a93c6f3ab8791e4a0fb0b30ffd560faaa3d32b892aa1acbaa70a1525208",
  "validation_ids_sha256": "e4022a2d7db1626e9937c9296b6faf5a9e777aecac260a526e9dd08b98c067b9",
  "monthly_auc": {
    "2024-01": {
      "rows": 70389,
      "positives": 12784,
      "auc": 0.674877873066096
    },
    "2024-02": {
      "rows": 70370,
      "positives": 12666,
      "auc": 0.683726287096462
    },
    "2024-03": {
      "rows": 91044,
      "positives": 16511,
      "auc": 0.6838897296374233
    },
    "2024-04": {
      "rows": 58204,
      "positives": 10540,
      "auc": 0.685740092093102
    },
    "2024-05": {
      "rows": 54105,
      "positives": 9706,
      "auc": 0.6831660568686686
    },
    "2024-06": {
      "rows": 52209,
      "positives": 9400,
      "auc": 0.686855160204431
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 23811,
      "positives": 4908,
      "auc": 0.6100372764813422
    },
    "channel_marketplace": {
      "rows": 94662,
      "positives": 22273,
      "auc": 0.6605879508188037
    },
    "channel_online": {
      "rows": 275944,
      "positives": 44054,
      "auc": 0.6832295994536854
    },
    "channel_store": {
      "rows": 1904,
      "positives": 372,
      "auc": 0.611060810241725
    },
    "unseen_customer": {
      "rows": 79622,
      "positives": 19593,
      "auc": 0.673174514078688
    },
    "seen_customer": {
      "rows": 316699,
      "positives": 52014,
      "auc": 0.6764263252235614
    }
  },
  "best_iterations": 3026,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 121.78812561099994
}
Run complete: /content/optiml_gpu_runs/jay/20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261013T192127Z_jul2024_stable_depth4_7f3d6e7e --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 4 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6058679	best: 0.6058679 (0)	total: 45.1ms	remaining: 3m 45s
100:	test: 0.6498463	best: 0.6498463 (100)	total: 3.1s	remaining: 2m 30s
200:	test: 0.6554509	best: 0.6554707 (199)	total: 5.88s	remaining: 2m 20s
300:	test: 0.6592541	best: 0.6592541 (300)	total: 8.97s	remaining: 2m 20s
400:	test: 0.6620144	best: 0.6620144 (400)	total: 13.2s	remaining: 2m 31s
500:	test: 0.6643120	best: 0.6643120 (500)	total: 16s	remaining: 2m 23s
600:	test: 0.6656000	best: 0.6656104 (591)	total: 18.8s	remaining: 2m 17s
700:	test: 0.6669868	best: 0.6669910 (696)	total: 21.5s	remaining: 2m 11s
800:	test: 0.6679282	best: 0.6679282 (800)	total: 25.5s	remaining: 2m 13s
900:	test: 0.6688041	best: 0.6688415 (894)	total: 28.8s	remaining: 2m 11s
1000:	test: 0.6692276	best: 0.6692276 (1000)	total: 31.6s	remaining: 2m 6s
1100:	test: 0.6700493	best: 0.6700527 (1099)	total: 34.3s	remaining: 2m 1s
1200:	test: 0.6703948	best: 0.6704787 (1180)	total: 37.1s	remaining: 1m 57s
1300:	test: 0.6709539	best: 0.6709539 (1300)	total: 41.4s	remaining: 1m 57s
1400:	test: 0.6715306	best: 0.6715306 (1400)	total: 44.2s	remaining: 1m 53s
1500:	test: 0.6718194	best: 0.6718258 (1492)	total: 46.9s	remaining: 1m 49s
1600:	test: 0.6723702	best: 0.6723759 (1598)	total: 49.7s	remaining: 1m 45s
1700:	test: 0.6754341	best: 0.6754346 (1699)	total: 53.1s	remaining: 1m 43s
1800:	test: 0.6756461	best: 0.6756461 (1800)	total: 56.9s	remaining: 1m 41s
1900:	test: 0.6760020	best: 0.6760138 (1899)	total: 59.7s	remaining: 1m 37s
2000:	test: 0.6788870	best: 0.6788870 (2000)	total: 1m 2s	remaining: 1m 33s
2100:	test: 0.6789782	best: 0.6789867 (2093)	total: 1m 5s	remaining: 1m 29s
2200:	test: 0.6791251	best: 0.6791338 (2187)	total: 1m 9s	remaining: 1m 27s
2300:	test: 0.6792489	best: 0.6792521 (2298)	total: 1m 12s	remaining: 1m 24s

In [26]:
next_metrics = {
    name: json.loads((path / "metrics.json").read_text())
    for name, path in next_paths.items()
}

next_summary = pd.DataFrame({
    name: {
        "auc": metric["auc"],
        "best_iterations": metric["best_iterations"],
    }
    for name, metric in next_metrics.items()
}).T

next_summary[["fold", "policy"]] = (
    next_summary.index.to_series().str.split("_", n=1, expand=True)
)

display(
    next_summary.pivot(
        index="policy",
        columns="fold",
        values="auc",
    )
)

fold                  jan2024   jul2024
policy
stable_depth4        0.673597  0.683985
stable_no_macro      0.680338  0.691674
stable_no_macro_age  0.681384  0.691085

In [10]:
from pathlib import Path
import json
import pandas as pd

RUN_ROOT = Path(
    "/content/drive/MyDrive/OptimlRuns/CatBoost/jay"
)

def find_run(label):
    matches = sorted(
        [
            path for path in RUN_ROOT.iterdir()
            if path.is_dir()
            and f"_{label}_" in path.name
            and (path / "COMPLETE.json").exists()
        ],
        key=lambda path: path.name,
    )

    if not matches:
        raise FileNotFoundError(f"No completed Drive run found for {label}")

    selected = matches[-1]
    print(label, "->", selected)
    return selected

next_paths = {
    "jan2024_stable_no_macro": find_run("jan2024_stable_no_macro"),
    "jul2024_stable_no_macro": find_run("jul2024_stable_no_macro"),
    "jan2024_stable_no_macro_age": find_run("jan2024_stable_no_macro_age"),
    "jul2024_stable_no_macro_age": find_run("jul2024_stable_no_macro_age"),
}

jan2024_stable_no_macro -> /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57
jul2024_stable_no_macro -> /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T192753Z_jul2024_stable_no_macro_age_21fea734
jan2024_stable_no_macro_age -> /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57
jul2024_stable_no_macro_age -> /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261013T192753Z_jul2024_stable_no_macro_age_21fea734

In [12]:
from pathlib import Path
import re

RUN_ROOT = Path(
    "/content/drive/MyDrive/OptimlRuns/CatBoost/jay"
)

def find_run_exact(label):
    pattern = re.compile(
        rf"^\d{{8}}T\d{{6}}Z_{re.escape(label)}_[0-9a-f]{{8}}$"
    )

    matches = sorted(
        path for path in RUN_ROOT.iterdir()
        if path.is_dir()
        and pattern.fullmatch(path.name)
        and (path / "COMPLETE.json").exists()
    )

    if not matches:
        raise FileNotFoundError(f"No completed run found for {label}")

    selected = matches[-1]
    print(label, "->", selected.name)
    return selected

next_paths = {
    "jan2024_stable_no_macro":
        find_run_exact("jan2024_stable_no_macro"),

    "jul2024_stable_no_macro":
        find_run_exact("jul2024_stable_no_macro"),

    "jan2024_stable_no_macro_age":
        find_run_exact("jan2024_stable_no_macro_age"),

    "jul2024_stable_no_macro_age":
        find_run_exact("jul2024_stable_no_macro_age"),
}

jan2024_stable_no_macro -> 20261013T191705Z_jan2024_stable_no_macro_c82dffbb
jul2024_stable_no_macro -> 20261013T192453Z_jul2024_stable_no_macro_391dd6e8
jan2024_stable_no_macro_age -> 20261013T191918Z_jan2024_stable_no_macro_age_0a8e7c57
jul2024_stable_no_macro_age -> 20261013T192753Z_jul2024_stable_no_macro_age_21fea734

In [13]:
from sklearn.metrics import roc_auc_score
import pandas as pd

def compare_stable_blends(fold):
    a = pd.read_parquet(
        next_paths[f"{fold}_stable_no_macro"]
        / "validation_predictions.parquet"
    ).rename(columns={"prediction": "no_macro"})

    b = pd.read_parquet(
        next_paths[f"{fold}_stable_no_macro_age"]
        / "validation_predictions.parquet"
    ).rename(columns={"prediction": "no_macro_age"})

    merged = a.merge(
        b[["order_line_id", "no_macro_age"]],
        on="order_line_id",
        validate="one_to_one",
    )

    rows = []

    for weight_age_removed in [0.0, 0.25, 0.50, 0.75, 1.0]:
        probability_blend = (
            weight_age_removed * merged["no_macro_age"]
            + (1 - weight_age_removed) * merged["no_macro"]
        )

        rank_blend = (
            weight_age_removed
            * merged["no_macro_age"].rank(pct=True)
            + (1 - weight_age_removed)
            * merged["no_macro"].rank(pct=True)
        )

        rows.append({
            "weight_age_removed": weight_age_removed,
            "probability_auc": roc_auc_score(
                merged["returned"], probability_blend
            ),
            "rank_auc": roc_auc_score(
                merged["returned"], rank_blend
            ),
        })

    return pd.DataFrame(rows).set_index("weight_age_removed")

print("January 2024 fold")
display(compare_stable_blends("jan2024"))

print("July 2024 fold")
display(compare_stable_blends("jul2024"))

January 2024 fold

                    probability_auc  rank_auc
weight_age_removed
0.00                       0.680338  0.680338
0.25                       0.681338  0.681394
0.50                       0.681858  0.681918
0.75                       0.681878  0.681912
1.00                       0.681384  0.681384

July 2024 fold

                    probability_auc  rank_auc
weight_age_removed
0.00                       0.691674  0.691674
0.25                       0.692409  0.692402
0.50                       0.692553  0.692542
0.75                       0.692105  0.692097
1.00                       0.691085  0.691085

In [14]:
from datetime import datetime, timezone
from pathlib import Path
import json
import pandas as pd
from sklearn.metrics import roc_auc_score

from optiml.train import write_submission
from optiml.prepare import sha256

stable_drops = [
    "customer_id",
    "product_id",
    "store_id",
    "product_supplier_code",
    "banner_id",
]

macro_drops = [
    "cpi",
    "fuel_price",
    "temperature_f",
    "unemployment",
    "fuel_surcharge",
]

age_drops = [
    "customer_tenure_days",
    "customer_tenure_days_invalid",
    "store_age_days",
    "store_age_days_invalid",
]

common_final = [
    "--cutoff", "2024-07-01",
    "--validation-months", "6",
    "--iterations", "5000",
    "--patience", "300",
    "--depth", "5",
    "--no-history",
]

final_no_macro = run_catboost(
    "stable_no_macro_final",
    common_final + [
        "--drop-features",
        *(stable_drops + macro_drops),
        "--finalize",
    ],
)

final_no_macro_age = run_catboost(
    "stable_no_macro_age_final",
    common_final + [
        "--drop-features",
        *(stable_drops + macro_drops + age_drops),
        "--finalize",
    ],
)

# Check the blend on the final validation predictions.
valid_a = pd.read_parquet(
    final_no_macro / "validation_predictions.parquet"
).rename(columns={"prediction": "prediction_a"})

valid_b = pd.read_parquet(
    final_no_macro_age / "validation_predictions.parquet"
).rename(columns={"prediction": "prediction_b"})

valid = valid_a.merge(
    valid_b[["order_line_id", "prediction_b"]],
    on="order_line_id",
    validate="one_to_one",
)

valid_blend = (
    0.5 * valid["prediction_a"].rank(method="average", pct=True)
    + 0.5 * valid["prediction_b"].rank(method="average", pct=True)
)

print(
    "Final blend validation AUC:",
    roc_auc_score(valid["returned"], valid_blend),
)

# Blend test predictions by rank.
test_a = pd.read_parquet(
    final_no_macro / "test_predictions.parquet"
).rename(columns={"prediction": "prediction_a"})

test_b = pd.read_parquet(
    final_no_macro_age / "test_predictions.parquet"
).rename(columns={"prediction": "prediction_b"})

test_blend = test_a.merge(
    test_b,
    on="order_line_id",
    validate="one_to_one",
)

blended_prediction = (
    0.5 * test_blend["prediction_a"].rank(method="average", pct=True)
    + 0.5 * test_blend["prediction_b"].rank(method="average", pct=True)
)

run_name = (
    datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    + "_stable_rank_blend"
)

ensemble_dir = DRIVE_RUNS / run_name
ensemble_dir.mkdir(parents=True, exist_ok=False)

sample = pd.read_csv(DATA / "sample_submission.csv")

write_submission(
    sample,
    test_blend["order_line_id"],
    blended_prediction,
    ensemble_dir / "submission.csv",
)

pd.DataFrame({
    "order_line_id": test_blend["order_line_id"],
    "prediction": blended_prediction,
}).to_parquet(
    ensemble_dir / "test_predictions.parquet",
    index=False,
)

manifest = {
    "model": "50/50 rank blend",
    "component_1": final_no_macro.name,
    "component_2": final_no_macro_age.name,
    "rows": len(test_blend),
    "validation_auc": float(
        roc_auc_score(valid["returned"], valid_blend)
    ),
    "submission_sha256": sha256(
        ensemble_dir / "submission.csv"
    ),
}

(ensemble_dir / "manifest.json").write_text(
    json.dumps(manifest, indent=2)
)

print(json.dumps(manifest, indent=2))
print("Submission:", ensemble_dir / "submission.csv")

Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261014T020829Z_stable_no_macro_final_4bdb7b48 --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id cpi fuel_price temperature_f unemployment fuel_surcharge --finalize
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6051904	best: 0.6051904 (0)	total: 49.8ms	remaining: 4m 8s
100:	test: 0.6506628	best: 0.6506628 (100)	total: 3.19s	remaining: 2m 34s
200:	test: 0.6584680	best: 0.6584680 (200)	total: 7.83s	remaining: 3m 6s
300:	test: 0.6625892	best: 0.6625892 (300)	total: 10.9s	remaining: 2m 50s
400:	test: 0.6655306	best: 0.6655306 (400)	total: 13.9s	remaining: 2m 39s
500:	test: 0.6671393	best: 0.6671393 (500)	total: 16.8s	remaining: 2m 31s
600:	test: 0.6703105	best: 0.6703113 (598)	total: 20.6s	remaining: 2m 30s
700:	test: 0.6715299	best: 0.6715379 (695)	total: 24.3s	remaining: 2m 28s
800:	test: 0.6727009	best: 0.6727033 (799)	total: 27.2s	remaining: 2m 22s
900:	test: 0.6734464	best: 0.6734464 (900)	total: 30.1s	remaining: 2m 16s
1000:	test: 0.6738953	best: 0.6738953 (1000)	total: 33.3s	remaining: 2m 12s
1100:	test: 0.6743459	best: 0.6743505 (1099)	total: 37.6s	remaining: 2m 13s
1200:	test: 0.6748630	best: 0.6748729 (1185)	total: 40.5s	remaining: 2m 8s
1300:	test: 0.6750784	best: 0.6750784 (1300)	total: 43.5s	remaining: 2m 3s
1400:	test: 0.6754148	best: 0.6754148 (1400)	total: 46.4s	remaining: 1m 59s
1500:	test: 0.6758128	best: 0.6758320 (1489)	total: 51.1s	remaining: 1m 59s
1600:	test: 0.6764892	best: 0.6764956 (1598)	total: 54s	remaining: 1m 54s
1700:	test: 0.6796096	best: 0.6796096 (1700)	total: 57s	remaining: 1m 50s
1800:	test: 0.6798109	best: 0.6798109 (1800)	total: 59.9s	remaining: 1m 46s
1900:	test: 0.6825590	best: 0.6825603 (1893)	total: 1m 4s	remaining: 1m 44s
2000:	test: 0.6851187	best: 0.6851205 (1999)	total: 1m 7s	remaining: 1m 41s
2100:	test: 0.6852610	best: 0.6852696 (2072)	total: 1m 10s	remaining: 1m 37s
2200:	test: 0.6854900	best: 0.6854900 (2200)	total: 1m 13s	remaining: 1m 33s
2300:	test: 0.6855936	best: 0.6855952 (2299)	total: 1m 17s	remaining: 1m 30s
2400:	test: 0.6856381	best: 0.6856409 (2388)	total: 1m 21s	remaining: 1m 27s
2500:	test: 0.6857544	best: 0.6857648 (2481)	total: 1m 24s	remaining: 1m 23s
2600:	test: 0.6858962	best: 0.6858962 (2600)	total: 1m 26s	remaining: 1m 20s
2700:	test: 0.6881267	best: 0.6881376 (2691)	total: 1m 30s	remaining: 1m 16s
2800:	test: 0.6901052	best: 0.6901102 (2794)	total: 1m 34s	remaining: 1m 14s
2900:	test: 0.6900922	best: 0.6901386 (2851)	total: 1m 37s	remaining: 1m 10s
3000:	test: 0.6917292	best: 0.6917309 (2992)	total: 1m 40s	remaining: 1m 6s
3100:	test: 0.6917870	best: 0.6917876 (3094)	total: 1m 43s	remaining: 1m 3s
3200:	test: 0.6917684	best: 0.6917948 (3119)	total: 1m 48s	remaining: 1m
3300:	test: 0.6917532	best: 0.6917993 (3244)	total: 1m 51s	remaining: 57.2s
3400:	test: 0.6918795	best: 0.6918812 (3395)	total: 1m 54s	remaining: 53.7s
3500:	test: 0.6920772	best: 0.6920922 (3464)	total: 1m 57s	remaining: 50.1s
3600:	test: 0.6919977	best: 0.6920922 (3464)	total: 2m 1s	remaining: 47.2s
3700:	test: 0.6920064	best: 0.6920922 (3464)	total: 2m 4s	remaining: 43.8s
bestTest = 0.6920921803
bestIteration = 3464
Shrink model to first 3465 iterations.
{
  "auc": 0.6920920732860322,
  "log_loss": 0.4372474254321103,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.6912593647301626
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.699492049540183
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6863469075827504
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6938938650112537
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.6935336014754641
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.6890791816597724
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6204846817064161
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.6700013024501994
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7041724975943269
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6039774689013624
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6773946953800281
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.6911414367211052
    }
  },
  "best_iterations": 3465,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 165.13335085500012
}
Refitting selected iteration count on labeled history...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	total: 62.1ms	remaining: 3m 35s
100:	total: 3.89s	remaining: 2m 9s
200:	total: 7.52s	remaining: 2m 2s
300:	total: 12.1s	remaining: 2m 7s
400:	total: 16s	remaining: 2m 2s
500:	total: 19.5s	remaining: 1m 55s
600:	total: 23.2s	remaining: 1m 50s
700:	total: 28s	remaining: 1m 50s
800:	total: 31.6s	remaining: 1m 45s
900:	total: 35.1s	remaining: 1m 40s
1000:	total: 39.2s	remaining: 1m 36s
1100:	total: 43.4s	remaining: 1m 33s
1200:	total: 46.9s	remaining: 1m 28s
1300:	total: 50.4s	remaining: 1m 23s
1400:	total: 54.9s	remaining: 1m 20s
1500:	total: 58.6s	remaining: 1m 16s
1600:	total: 1m 2s	remaining: 1m 12s
1700:	total: 1m 5s	remaining: 1m 8s
1800:	total: 1m 10s	remaining: 1m 5s
1900:	total: 1m 13s	remaining: 1m
2000:	total: 1m 17s	remaining: 56.7s
2100:	total: 1m 21s	remaining: 52.7s
2200:	total: 1m 25s	remaining: 49.1s
2300:	total: 1m 29s	remaining: 45s
2400:	total: 1m 32s	remaining: 41s
2500:	total: 1m 36s	remaining: 37.3s
2600:	total: 1m 40s	remaining: 33.5s
2700:	total: 1m 44s	remaining: 29.5s
2800:	total: 1m 47s	remaining: 25.5s
2900:	total: 1m 52s	remaining: 21.8s
3000:	total: 1m 55s	remaining: 17.9s
3100:	total: 1m 59s	remaining: 14s
3200:	total: 2m 2s	remaining: 10.1s
3300:	total: 2m 7s	remaining: 6.34s
3400:	total: 2m 11s	remaining: 2.47s
3464:	total: 2m 13s	remaining: 0us
Run complete: /content/optiml_gpu_runs/jay/20261014T020829Z_stable_no_macro_final_4bdb7b48
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261014T020829Z_stable_no_macro_final_4bdb7b48
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261014T021418Z_stable_no_macro_age_final_ea07af7a --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id cpi fuel_price temperature_f unemployment fuel_surcharge customer_tenure_days customer_tenure_days_invalid store_age_days store_age_days_invalid --finalize
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6110593	best: 0.6110593 (0)	total: 64.3ms	remaining: 5m 21s
100:	test: 0.6499133	best: 0.6499216 (99)	total: 3.39s	remaining: 2m 44s
200:	test: 0.6564628	best: 0.6564628 (200)	total: 6.44s	remaining: 2m 33s
300:	test: 0.6598967	best: 0.6598967 (300)	total: 9.48s	remaining: 2m 27s
400:	test: 0.6630873	best: 0.6630873 (400)	total: 13.9s	remaining: 2m 39s
500:	test: 0.6658162	best: 0.6658162 (500)	total: 17.2s	remaining: 2m 34s
600:	test: 0.6712427	best: 0.6712503 (598)	total: 20.2s	remaining: 2m 27s
700:	test: 0.6722318	best: 0.6722318 (700)	total: 23.1s	remaining: 2m 21s
800:	test: 0.6730452	best: 0.6730452 (800)	total: 27.1s	remaining: 2m 22s
900:	test: 0.6736002	best: 0.6736024 (899)	total: 30.8s	remaining: 2m 20s
1000:	test: 0.6739132	best: 0.6739223 (999)	total: 33.9s	remaining: 2m 15s
1100:	test: 0.6747669	best: 0.6747669 (1100)	total: 36.9s	remaining: 2m 10s
1200:	test: 0.6752446	best: 0.6752509 (1197)	total: 40.3s	remaining: 2m 7s
1300:	test: 0.6756021	best: 0.6756029 (1299)	total: 44.6s	remaining: 2m 6s
1400:	test: 0.6760161	best: 0.6760161 (1400)	total: 47.5s	remaining: 2m 2s
1500:	test: 0.6764183	best: 0.6764204 (1499)	total: 50.5s	remaining: 1m 57s
1600:	test: 0.6769841	best: 0.6769850 (1597)	total: 53.5s	remaining: 1m 53s
1700:	test: 0.6775877	best: 0.6775877 (1700)	total: 58.1s	remaining: 1m 52s
1800:	test: 0.6777313	best: 0.6777313 (1800)	total: 1m 1s	remaining: 1m 48s
1900:	test: 0.6804481	best: 0.6804492 (1899)	total: 1m 3s	remaining: 1m 44s
2000:	test: 0.6829234	best: 0.6829265 (1999)	total: 1m 6s	remaining: 1m 40s
2100:	test: 0.6830884	best: 0.6830897 (2098)	total: 1m 11s	remaining: 1m 38s
2200:	test: 0.6831504	best: 0.6831504 (2200)	total: 1m 14s	remaining: 1m 34s
2300:	test: 0.6832153	best: 0.6832315 (2293)	total: 1m 17s	remaining: 1m 30s
2400:	test: 0.6832501	best: 0.6832714 (2386)	total: 1m 20s	remaining: 1m 27s
2500:	test: 0.6833242	best: 0.6833503 (2467)	total: 1m 24s	remaining: 1m 24s
2600:	test: 0.6835004	best: 0.6835004 (2600)	total: 1m 27s	remaining: 1m 21s
2700:	test: 0.6856124	best: 0.6856265 (2666)	total: 1m 30s	remaining: 1m 17s
2800:	test: 0.6875710	best: 0.6875755 (2793)	total: 1m 33s	remaining: 1m 13s
2900:	test: 0.6875383	best: 0.6875755 (2793)	total: 1m 37s	remaining: 1m 10s
3000:	test: 0.6875524	best: 0.6875902 (2963)	total: 1m 41s	remaining: 1m 7s
3100:	test: 0.6894023	best: 0.6894023 (3100)	total: 1m 44s	remaining: 1m 3s
3200:	test: 0.6893710	best: 0.6894337 (3119)	total: 1m 47s	remaining: 1m
3300:	test: 0.6893789	best: 0.6894337 (3119)	total: 1m 50s	remaining: 56.8s
3400:	test: 0.6894086	best: 0.6894337 (3119)	total: 1m 54s	remaining: 53.9s
bestTest = 0.6894337237
bestIteration = 3119
Shrink model to first 3120 iterations.
{
  "auc": 0.6894337000944224,
  "log_loss": 0.4379783168622925,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.6871622638725541
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.6968799778803267
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6849348334321967
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6928494997454637
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.6889445747595266
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.6866844797978955
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6161008346095649
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.668312672589616
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7012859079547694
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.5946177900977597
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6778632887899394
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.6893822030277255
    }
  },
  "best_iterations": 3120,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 155.75666303799994
}
Refitting selected iteration count on labeled history...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	total: 51.2ms	remaining: 2m 39s
100:	total: 4.76s	remaining: 2m 22s
200:	total: 8.79s	remaining: 2m 7s
300:	total: 12.4s	remaining: 1m 55s
400:	total: 16s	remaining: 1m 48s
500:	total: 20.8s	remaining: 1m 48s
600:	total: 24.5s	remaining: 1m 42s
700:	total: 28s	remaining: 1m 36s
800:	total: 32.1s	remaining: 1m 33s
900:	total: 36.4s	remaining: 1m 29s
1000:	total: 39.9s	remaining: 1m 24s
1100:	total: 43.4s	remaining: 1m 19s
1200:	total: 47.9s	remaining: 1m 16s
1300:	total: 51.6s	remaining: 1m 12s
1400:	total: 55.1s	remaining: 1m 7s
1500:	total: 58.6s	remaining: 1m 3s
1600:	total: 1m 3s	remaining: 1m
1700:	total: 1m 6s	remaining: 55.8s
1800:	total: 1m 10s	remaining: 51.5s
1900:	total: 1m 13s	remaining: 47.4s
2000:	total: 1m 18s	remaining: 43.9s
2100:	total: 1m 22s	remaining: 39.8s
2200:	total: 1m 25s	remaining: 35.7s
2300:	total: 1m 29s	remaining: 31.9s
2400:	total: 1m 33s	remaining: 28.1s
2500:	total: 1m 37s	remaining: 24.1s
2600:	total: 1m 40s	remaining: 20.1s
2700:	total: 1m 45s	remaining: 16.3s
2800:	total: 1m 48s	remaining: 12.4s
2900:	total: 1m 52s	remaining: 8.49s
3000:	total: 1m 55s	remaining: 4.6s
3100:	total: 2m	remaining: 739ms
3119:	total: 2m 1s	remaining: 0us
Run complete: /content/optiml_gpu_runs/jay/20261014T021418Z_stable_no_macro_age_final_ea07af7a
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261014T021418Z_stable_no_macro_age_final_ea07af7a
Final blend validation AUC: 0.6918823367741374
{
  "model": "50/50 rank blend",
  "component_1": "20261014T020829Z_stable_no_macro_final_4bdb7b48",
  "component_2": "20261014T021418Z_stable_no_macro_age_final_ea07af7a",
  "rows": 479995,
  "validation_auc": 0.6918823367741374,
  "submission_sha256": "2082b247cb3a47ce1970c376a15ef35e326633c708a34156aa8a12b762e0efc4"
}
Submission: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261014T021945Z_stable_rank_blend/submission.csv

In [15]:
import numpy as np
import pandas as pd
from sklearn.metrics import roc_auc_score

base_run = find_run_exact("stable_core_final")

stable_drops = [
    "customer_id",
    "product_id",
    "store_id",
    "product_supplier_code",
    "banner_id",
]

seed_runs = {
    "seed42": base_run,
}

for seed in [7, 2026]:
    seed_runs[f"seed{seed}"] = run_catboost(
        f"stable_core_seed{seed}_final",
        [
            "--cutoff", "2024-07-01",
            "--validation-months", "6",
            "--iterations", "5000",
            "--patience", "300",
            "--depth", "5",
            "--seed", str(seed),
            "--no-history",
            "--drop-features", *stable_drops,
            "--finalize",
        ],
    )

validation = None
prediction_columns = []

for name, path in seed_runs.items():
    frame = pd.read_parquet(
        path / "validation_predictions.parquet"
    )[[
        "order_line_id",
        "returned",
        "_month",
        "prediction",
    ]]

    prediction_name = f"prediction_{name}"
    frame = frame.rename(
        columns={"prediction": prediction_name}
    )

    if validation is None:
        validation = frame
    else:
        validation = validation.merge(
            frame[["order_line_id", prediction_name]],
            on="order_line_id",
            validate="one_to_one",
        )

    prediction_columns.append(prediction_name)

for column in prediction_columns:
    validation[f"rank_{column}"] = (
        validation[column].rank(method="average", pct=True)
    )

rank_columns = [
    f"rank_{column}" for column in prediction_columns
]

validation["seed_ensemble"] = (
    validation[rank_columns].mean(axis=1)
)

print("Individual validation AUCs:")
for column in prediction_columns:
    print(
        column,
        roc_auc_score(
            validation["returned"],
            validation[column],
        ),
    )

print(
    "Three-seed rank ensemble AUC:",
    roc_auc_score(
        validation["returned"],
        validation["seed_ensemble"],
    ),
)

monthly = {}
for month in sorted(validation["_month"].unique()):
    mask = validation["_month"].eq(month)
    monthly[month] = roc_auc_score(
        validation.loc[mask, "returned"],
        validation.loc[mask, "seed_ensemble"],
    )

display(pd.Series(monthly, name="ensemble_auc"))

stable_core_final -> 20261013T185758Z_stable_core_final_a9c89e5f
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261014T023216Z_stable_core_seed7_final_1b67dc0c --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --seed 7 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id --finalize
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6056317	best: 0.6056317 (0)	total: 51.4ms	remaining: 4m 16s
100:	test: 0.6519556	best: 0.6519556 (100)	total: 3.24s	remaining: 2m 37s
200:	test: 0.6587065	best: 0.6587065 (200)	total: 6.31s	remaining: 2m 30s
300:	test: 0.6631208	best: 0.6631208 (300)	total: 9.27s	remaining: 2m 24s
400:	test: 0.6659085	best: 0.6659352 (390)	total: 13.8s	remaining: 2m 38s
500:	test: 0.6684087	best: 0.6684087 (500)	total: 16.9s	remaining: 2m 31s
600:	test: 0.6692918	best: 0.6692918 (600)	total: 19.8s	remaining: 2m 25s
700:	test: 0.6705919	best: 0.6705919 (700)	total: 22.8s	remaining: 2m 19s
800:	test: 0.6715085	best: 0.6715085 (800)	total: 26.6s	remaining: 2m 19s
900:	test: 0.6733496	best: 0.6733496 (900)	total: 30.3s	remaining: 2m 17s
1000:	test: 0.6739910	best: 0.6739910 (1000)	total: 33.2s	remaining: 2m 12s
1100:	test: 0.6747876	best: 0.6747898 (1096)	total: 36.2s	remaining: 2m 8s
1200:	test: 0.6752945	best: 0.6753058 (1198)	total: 39.4s	remaining: 2m 4s
1300:	test: 0.6786197	best: 0.6786197 (1300)	total: 43.6s	remaining: 2m 4s
1400:	test: 0.6789246	best: 0.6789246 (1400)	total: 46.5s	remaining: 1m 59s
1500:	test: 0.6790926	best: 0.6790954 (1496)	total: 49.5s	remaining: 1m 55s
1600:	test: 0.6792903	best: 0.6792925 (1599)	total: 52.4s	remaining: 1m 51s
1700:	test: 0.6797248	best: 0.6797255 (1699)	total: 57.1s	remaining: 1m 50s
1800:	test: 0.6799017	best: 0.6799017 (1800)	total: 1m	remaining: 1m 46s
1900:	test: 0.6800796	best: 0.6800796 (1900)	total: 1m 3s	remaining: 1m 42s
2000:	test: 0.6800807	best: 0.6800982 (1955)	total: 1m 6s	remaining: 1m 38s
2100:	test: 0.6804499	best: 0.6804573 (2095)	total: 1m 10s	remaining: 1m 36s
2200:	test: 0.6806931	best: 0.6807278 (2183)	total: 1m 13s	remaining: 1m 33s
2300:	test: 0.6832634	best: 0.6832668 (2293)	total: 1m 16s	remaining: 1m 29s
2400:	test: 0.6832738	best: 0.6833074 (2342)	total: 1m 19s	remaining: 1m 26s
2500:	test: 0.6834017	best: 0.6834073 (2494)	total: 1m 22s	remaining: 1m 22s
2600:	test: 0.6835552	best: 0.6835552 (2600)	total: 1m 27s	remaining: 1m 20s
2700:	test: 0.6858348	best: 0.6858351 (2649)	total: 1m 30s	remaining: 1m 16s
2800:	test: 0.6858952	best: 0.6859000 (2774)	total: 1m 33s	remaining: 1m 13s
2900:	test: 0.6860402	best: 0.6860532 (2884)	total: 1m 36s	remaining: 1m 9s
3000:	test: 0.6880552	best: 0.6880647 (2970)	total: 1m 40s	remaining: 1m 7s
3100:	test: 0.6881352	best: 0.6881394 (3098)	total: 1m 43s	remaining: 1m 3s
3200:	test: 0.6882141	best: 0.6882561 (3191)	total: 1m 46s	remaining: 1m
3800:	test: 0.6885757	best: 0.6885781 (3795)	total: 2m 6s	remaining: 40s
3900:	test: 0.6886482	best: 0.6886525 (3872)	total: 2m 11s	remaining: 36.9s
4000:	test: 0.6887730	best: 0.6887730 (4000)	total: 2m 13s	remaining: 33.4s
4100:	test: 0.6888016	best: 0.6888180 (4054)	total: 2m 16s	remaining: 30s
4200:	test: 0.6888777	best: 0.6888879 (4172)	total: 2m 20s	remaining: 26.6s
4300:	test: 0.6890003	best: 0.6890071 (4262)	total: 2m 24s	remaining: 23.5s
4400:	test: 0.6890420	best: 0.6890496 (4355)	total: 2m 27s	remaining: 20.1s
4500:	test: 0.6890687	best: 0.6890740 (4463)	total: 2m 30s	remaining: 16.7s
4600:	test: 0.6891312	best: 0.6891312 (4600)	total: 2m 33s	remaining: 13.3s
4700:	test: 0.6890785	best: 0.6891312 (4600)	total: 2m 38s	remaining: 10.1s
4800:	test: 0.6890338	best: 0.6891312 (4600)	total: 2m 41s	remaining: 6.68s
4900:	test: 0.6891121	best: 0.6891312 (4600)	total: 2m 44s	remaining: 3.32s
bestTest = 0.6891312003
bestIteration = 4600
Shrink model to first 4601 iterations.
{
  "auc": 0.6891311948633315,
  "log_loss": 0.43810184554354814,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.6916348498298709
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.6941969421149422
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6795455936437382
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6888775790039006
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.6918883862474998
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.6895788399053275
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6191915237916039
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.6672708292981326
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.7008238507379706
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6037703090627498
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6737589460262519
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.6877013423860886
    }
  },
  "best_iterations": 4601,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 205.78431997400003
}
Refitting selected iteration count on labeled history...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	total: 53.2ms	remaining: 4m 4s
100:	total: 3.96s	remaining: 2m 56s
200:	total: 7.82s	remaining: 2m 51s
300:	total: 12.5s	remaining: 2m 58s
400:	total: 16.2s	remaining: 2m 49s
500:	total: 19.8s	remaining: 2m 42s
600:	total: 24.1s	remaining: 2m 40s
700:	total: 28.3s	remaining: 2m 37s
800:	total: 31.9s	remaining: 2m 31s
900:	total: 35.4s	remaining: 2m 25s
1000:	total: 39.8s	remaining: 2m 23s
1100:	total: 43.5s	remaining: 2m 18s
1200:	total: 47.1s	remaining: 2m 13s
1300:	total: 50.6s	remaining: 2m 8s
1400:	total: 55.3s	remaining: 2m 6s
1500:	total: 58.9s	remaining: 2m 1s
1600:	total: 1m 2s	remaining: 1m 56s
1700:	total: 1m 6s	remaining: 1m 52s
1800:	total: 1m 10s	remaining: 1m 49s
1900:	total: 1m 14s	remaining: 1m 45s
2000:	total: 1m 17s	remaining: 1m 40s
2100:	total: 1m 21s	remaining: 1m 37s
2200:	total: 1m 25s	remaining: 1m 33s
2300:	total: 1m 29s	remaining: 1m 29s
2400:	total: 1m 32s	remaining: 1m 25s
2500:	total: 1m 37s	remaining: 1m 21s
2600:	total: 1m 41s	remaining: 1m 17s
2700:	total: 1m 44s	remaining: 1m 13s
2800:	total: 1m 48s	remaining: 1m 9s
2900:	total: 1m 52s	remaining: 1m 6s
3000:	total: 1m 56s	remaining: 1m 2s
3100:	total: 1m 59s	remaining: 58s
3200:	total: 2m 3s	remaining: 54.2s
3300:	total: 2m 8s	remaining: 50.5s
3400:	total: 2m 11s	remaining: 46.5s
3500:	total: 2m 15s	remaining: 42.5s
3600:	total: 2m 19s	remaining: 38.8s
3700:	total: 2m 23s	remaining: 34.9s
3800:	total: 2m 27s	remaining: 31s
3900:	total: 2m 30s	remaining: 27s
4000:	total: 2m 35s	remaining: 23.3s
4100:	total: 2m 38s	remaining: 19.4s
4200:	total: 2m 42s	remaining: 15.5s
4300:	total: 2m 46s	remaining: 11.6s
4400:	total: 2m 50s	remaining: 7.75s
4500:	total: 2m 54s	remaining: 3.87s
4600:	total: 2m 57s	remaining: 0us
Run complete: /content/optiml_gpu_runs/jay/20261014T023216Z_stable_core_seed7_final_1b67dc0c
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261014T023216Z_stable_core_seed7_final_1b67dc0c
Running: /usr/bin/python3 -u -m optiml.train --prepared-dir /content/optiml_prepared/catboost-baseline-v1 --output-dir /content/optiml_gpu_runs/jay/20261014T023931Z_stable_core_seed2026_final_4863b5b9 --model catboost --device GPU --threads 2 --cutoff 2024-07-01 --validation-months 6 --iterations 5000 --patience 300 --depth 5 --seed 2026 --no-history --drop-features customer_id product_id store_id product_supplier_code banner_id --finalize
Loading prepared training features...
Fit 1,048,082 rows; validate 351,909 rows. Building model inputs...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	test: 0.6041658	best: 0.6041658 (0)	total: 52.9ms	remaining: 4m 24s
100:	test: 0.6518080	best: 0.6518080 (100)	total: 3.27s	remaining: 2m 38s
200:	test: 0.6594640	best: 0.6594640 (200)	total: 6.35s	remaining: 2m 31s
300:	test: 0.6640265	best: 0.6640265 (300)	total: 10.1s	remaining: 2m 37s
400:	test: 0.6668392	best: 0.6668392 (400)	total: 14.2s	remaining: 2m 42s
500:	test: 0.6696104	best: 0.6696104 (500)	total: 17.2s	remaining: 2m 34s
600:	test: 0.6709243	best: 0.6709258 (599)	total: 20.2s	remaining: 2m 27s
700:	test: 0.6718491	best: 0.6718491 (700)	total: 23.5s	remaining: 2m 24s
800:	test: 0.6727444	best: 0.6727452 (799)	total: 27.9s	remaining: 2m 26s
900:	test: 0.6733090	best: 0.6733201 (896)	total: 30.9s	remaining: 2m 20s
1000:	test: 0.6738698	best: 0.6738768 (991)	total: 33.9s	remaining: 2m 15s
1100:	test: 0.6748952	best: 0.6749113 (1099)	total: 37s	remaining: 2m 10s
1200:	test: 0.6754643	best: 0.6754643 (1200)	total: 41.8s	remaining: 2m 12s
1300:	test: 0.6758291	best: 0.6758291 (1300)	total: 44.8s	remaining: 2m 7s
1400:	test: 0.6761537	best: 0.6761537 (1400)	total: 47.8s	remaining: 2m 2s
1500:	test: 0.6763310	best: 0.6763384 (1496)	total: 50.7s	remaining: 1m 58s
1600:	test: 0.6762965	best: 0.6764260 (1579)	total: 54.9s	remaining: 1m 56s
1700:	test: 0.6798670	best: 0.6798813 (1696)	total: 58.3s	remaining: 1m 53s
1800:	test: 0.6801777	best: 0.6801813 (1778)	total: 1m 1s	remaining: 1m 48s
1900:	test: 0.6803951	best: 0.6803951 (1900)	total: 1m 4s	remaining: 1m 44s
2000:	test: 0.6830790	best: 0.6830792 (1997)	total: 1m 7s	remaining: 1m 41s
2100:	test: 0.6830746	best: 0.6832233 (2091)	total: 1m 11s	remaining: 1m 39s
2200:	test: 0.6831556	best: 0.6832233 (2091)	total: 1m 14s	remaining: 1m 35s
2300:	test: 0.6831605	best: 0.6832233 (2091)	total: 1m 17s	remaining: 1m 31s
2400:	test: 0.6832712	best: 0.6832713 (2399)	total: 1m 20s	remaining: 1m 27s
2500:	test: 0.6833746	best: 0.6833792 (2488)	total: 1m 25s	remaining: 1m 25s
2600:	test: 0.6834994	best: 0.6834994 (2600)	total: 1m 28s	remaining: 1m 21s
2700:	test: 0.6836170	best: 0.6836170 (2700)	total: 1m 31s	remaining: 1m 17s
2800:	test: 0.6836343	best: 0.6836451 (2782)	total: 1m 34s	remaining: 1m 13s
2900:	test: 0.6837406	best: 0.6837437 (2874)	total: 1m 38s	remaining: 1m 11s
3000:	test: 0.6838475	best: 0.6838623 (2978)	total: 1m 41s	remaining: 1m 7s
3100:	test: 0.6838767	best: 0.6838798 (3080)	total: 1m 44s	remaining: 1m 4s
3200:	test: 0.6839953	best: 0.6839955 (3198)	total: 1m 47s	remaining: 1m
3300:	test: 0.6840236	best: 0.6840519 (3246)	total: 1m 50s	remaining: 57.1s
3400:	test: 0.6839994	best: 0.6840519 (3246)	total: 1m 55s	remaining: 54.1s
3500:	test: 0.6842867	best: 0.6842916 (3495)	total: 1m 58s	remaining: 50.5s
3600:	test: 0.6843208	best: 0.6843611 (3584)	total: 2m 1s	remaining: 47s
3700:	test: 0.6843204	best: 0.6843611 (3584)	total: 2m 4s	remaining: 43.5s
3800:	test: 0.6844107	best: 0.6844372 (3719)	total: 2m 8s	remaining: 40.6s
3900:	test: 0.6845826	best: 0.6845873 (3897)	total: 2m 11s	remaining: 37.1s
4000:	test: 0.6846674	best: 0.6846755 (3997)	total: 2m 14s	remaining: 33.6s
4100:	test: 0.6847019	best: 0.6847211 (4076)	total: 2m 17s	remaining: 30.1s
4200:	test: 0.6847788	best: 0.6847854 (4197)	total: 2m 21s	remaining: 27s
4300:	test: 0.6849231	best: 0.6849390 (4297)	total: 2m 25s	remaining: 23.6s
4400:	test: 0.6849239	best: 0.6849390 (4297)	total: 2m 28s	remaining: 20.2s
4500:	test: 0.6849735	best: 0.6849735 (4500)	total: 2m 31s	remaining: 16.8s
4600:	test: 0.6849958	best: 0.6849959 (4598)	total: 2m 34s	remaining: 13.4s
4700:	test: 0.6850135	best: 0.6850678 (4689)	total: 2m 38s	remaining: 10.1s
4800:	test: 0.6850324	best: 0.6850678 (4689)	total: 2m 41s	remaining: 6.7s
4900:	test: 0.6850817	best: 0.6850893 (4859)	total: 2m 44s	remaining: 3.33s
4999:	test: 0.6851148	best: 0.6851293 (4966)	total: 2m 48s	remaining: 0us
bestTest = 0.6851293445
bestIteration = 4966
Shrink model to first 4967 iterations.
{
  "auc": 0.685129270969344,
  "log_loss": 0.43958542754159274,
  "fit_rows": 1048082,
  "validation_rows": 351909,
  "fit_positive_rate": 0.1803389429453039,
  "validation_positive_rate": 0.18108374608208372,
  "fit_ids_sha256": "d5ae74902fe3ee879b9af17b51059063b1f4196b843a69ecdf6c6e7158ab4e6a",
  "validation_ids_sha256": "88bb499cb5b048865072f8631f7c992c5da0b5ba875bf61a37d94714ddc3d564",
  "monthly_auc": {
    "2024-07": {
      "rows": 59589,
      "positives": 10757,
      "auc": 0.6856902728827496
    },
    "2024-08": {
      "rows": 58214,
      "positives": 10560,
      "auc": 0.6887577146215587
    },
    "2024-09": {
      "rows": 55090,
      "positives": 9937,
      "auc": 0.6759203806517772
    },
    "2024-10": {
      "rows": 61345,
      "positives": 11256,
      "auc": 0.6855447427956347
    },
    "2024-11": {
      "rows": 58821,
      "positives": 10517,
      "auc": 0.6890114706632958
    },
    "2024-12": {
      "rows": 58850,
      "positives": 10698,
      "auc": 0.6870343584040952
    }
  },
  "cohorts": {
    "channel_catalog": {
      "rows": 24801,
      "positives": 4660,
      "auc": 0.6146993843617092
    },
    "channel_marketplace": {
      "rows": 109455,
      "positives": 23766,
      "auc": 0.6637086828521509
    },
    "channel_online": {
      "rows": 215805,
      "positives": 34964,
      "auc": 0.6964998204523936
    },
    "channel_store": {
      "rows": 1848,
      "positives": 335,
      "auc": 0.6011265549318839
    },
    "unseen_customer": {
      "rows": 67564,
      "positives": 15605,
      "auc": 0.6697795606829946
    },
    "seen_customer": {
      "rows": 284345,
      "positives": 48120,
      "auc": 0.6834028300153064
    }
  },
  "best_iterations": 4967,
  "sample_order_fraction": 1.0,
  "validation_elapsed_seconds": 209.44330796300028
}
Refitting selected iteration count on labeled history...
Training catboost with backend {'task_type': 'GPU', 'devices': '0'}
Default metric period is 5 because AUC is/are not implemented for GPU
0:	total: 49.9ms	remaining: 4m 7s
100:	total: 4.14s	remaining: 3m 19s
200:	total: 8.8s	remaining: 3m 28s
300:	total: 12.4s	remaining: 3m 13s
400:	total: 16.1s	remaining: 3m 2s
500:	total: 20.6s	remaining: 3m 3s
600:	total: 24.6s	remaining: 2m 58s
700:	total: 28.1s	remaining: 2m 51s
800:	total: 31.7s	remaining: 2m 45s
900:	total: 36.5s	remaining: 2m 44s
1000:	total: 40s	remaining: 2m 38s
1100:	total: 43.6s	remaining: 2m 33s
1200:	total: 47.7s	remaining: 2m 29s
1300:	total: 51.9s	remaining: 2m 26s
1400:	total: 55.4s	remaining: 2m 21s
1500:	total: 58.9s	remaining: 2m 16s
1600:	total: 1m 3s	remaining: 2m 13s
1700:	total: 1m 7s	remaining: 2m 9s
1800:	total: 1m 10s	remaining: 2m 4s
1900:	total: 1m 14s	remaining: 2m
2000:	total: 1m 19s	remaining: 1m 57s
2100:	total: 1m 22s	remaining: 1m 52s
2200:	total: 1m 26s	remaining: 1m 48s
2300:	total: 1m 30s	remaining: 1m 44s
2400:	total: 1m 34s	remaining: 1m 41s
2500:	total: 1m 38s	remaining: 1m 36s
2600:	total: 1m 41s	remaining: 1m 32s
2700:	total: 1m 45s	remaining: 1m 28s
2800:	total: 1m 49s	remaining: 1m 24s
2900:	total: 1m 53s	remaining: 1m 20s
3000:	total: 1m 56s	remaining: 1m 16s
3100:	total: 2m 1s	remaining: 1m 13s
3200:	total: 2m 5s	remaining: 1m 8s
3300:	total: 2m 8s	remaining: 1m 4s
3400:	total: 2m 12s	remaining: 1m
3500:	total: 2m 16s	remaining: 57.3s
3600:	total: 2m 20s	remaining: 53.2s
3700:	total: 2m 23s	remaining: 49.2s
3800:	total: 2m 27s	remaining: 45.3s
3900:	total: 2m 31s	remaining: 41.5s
4000:	total: 2m 35s	remaining: 37.5s
4100:	total: 2m 38s	remaining: 33.6s
4200:	total: 2m 43s	remaining: 29.8s
4300:	total: 2m 47s	remaining: 25.9s
4400:	total: 2m 50s	remaining: 22s
4500:	total: 2m 54s	remaining: 18s
4600:	total: 2m 58s	remaining: 14.2s
4700:	total: 3m 2s	remaining: 10.3s
4800:	total: 3m 5s	remaining: 6.42s
4900:	total: 3m 9s	remaining: 2.55s
4966:	total: 3m 12s	remaining: 0us
Run complete: /content/optiml_gpu_runs/jay/20261014T023931Z_stable_core_seed2026_final_4863b5b9
Backup location: /content/drive/MyDrive/OptimlRuns/CatBoost/jay/20261014T023931Z_stable_core_seed2026_final_4863b5b9
Individual validation AUCs:
prediction_seed42 0.690251336960769
prediction_seed7 0.6891311948633315
prediction_seed2026 0.685129270969344
Three-seed rank ensemble AUC: 0.6889487898227961

2024-07    0.690785
2024-08    0.693298
2024-09    0.679369
2024-10    0.688923
2024-11    0.692306
2024-12    0.690108
Name: ensemble_auc, dtype: float64

## Final refit and submission audit

Choose only a validated configuration. Finalization refits on all labeled lines and writes
all 479,995 test predictions. The audit checks order IDs and probabilities before submission.

In [18]:
FINALIZE = False
SELECTED = "baseline_depth6"  # Change after inspecting full and recent validation.
if FINALIZE:
    if SELECTED not in trial_specs:
        raise ValueError("SELECTED has not been evaluated in this session")
    final_run = run_catboost(SELECTED + "_final", common + trial_specs[SELECTED] + ["--finalize"])
    subprocess.run([sys.executable, "-m", "optiml.audit_submission", "--csv", str(final_run / "submission.csv"),
                    "--run-dir", str(final_run), "--sample", str(DATA / "sample_submission.csv")], cwd=REPO, check=True)
    print("Use this exact backed-up CSV:", DRIVE_RUNS / final_run.name / "submission.csv")
else:
    print("Finalization is off during model selection.")

Finalization is off during model selection.